/* This is an autogenerated PetriNet Java file. */
package org.uam.aida.tscc.OP_models;
import java.util.Collections;
import java.util.stream.Stream;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.stream.Collectors;
import org.uam.aida.tscc.business.*;
import org.uam.aida.tscc.APFE.TSWFnet.TSWFNet;
import org.uam.aida.tscc.APFE.timeseries_guards.*;
import org.uam.aida.tscc.APFE.time_series_log.LogEntry;
import com.moandjiezana.toml.Toml;
import static org.uam.aida.tscc.APFE.timeseries_guards.LogicalTSG.LogicalExpression;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.google.common.collect.Range;

public class SHEERER_SINGLE_CYCLE extends TSWFNet {

  private static final Logger LOG = Logger.getLogger(SHEERER_SINGLE_CYCLE.class.getName());
  /** Custom declarations. */

  /** Places declaration. */
  private Place p15 = new Place("p15");
  private Place p21 = new Place("p21");
  private Place p24 = new Place("p24");
  private Place p1 = new Place("p1");
  private Place p2 = new Place("p2");
  private Place p3 = new Place("p3");
  private Place p4 = new Place("p4");
  private Place p30 = new Place("p30");
  private Place p35 = new Place("p35");

  /** Transitions declaration. */
  private Transition t14 = new Transition("t14","return true;","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return true;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t18 = new Transition("t18","return true;","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return true;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t19 = new Transition("t19","return true;","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return true;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t25 = new Transition("t25","return true;","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return true;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t5 = new Transition("t5","return true;","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return true;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t6 = new Transition("t6","return true;","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return true;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t7 = new Transition("t7","return true;","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return true;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t32 = new Transition("t32","return true;","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return true;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t34 = new Transition("t34","return true;","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return true;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };

  /** Input Arcs declaration. */
  private InputArc i12_p3_t7 = new InputArc("i12_p3_t7",p3,t7, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i33_p30_t32 = new InputArc("i33_p30_t32",p30,t32, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i28_p24_t25 = new InputArc("i28_p24_t25",p24,t25, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i10_p2_t6 = new InputArc("i10_p2_t6",p2,t6, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i35_p35_t34 = new InputArc("i35_p35_t34",p35,t34, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i22_p21_t18 = new InputArc("i22_p21_t18",p21,t18, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i26_p1_t5 = new InputArc("i26_p1_t5",p1,t5, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i37_p35_t19 = new InputArc("i37_p35_t19",p35,t19, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i16_p4_t14 = new InputArc("i16_p4_t14",p4,t14, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };

  /** Output Arcs declaration. */
  private OutputArc o29_t25_p2 = new OutputArc("o29_t25_p2",p2,t25, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o36_t7_p35 = new OutputArc("o36_t7_p35",p35,t7, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o34_t32_p3 = new OutputArc("o34_t32_p3",p3,t32, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o20_t19_p4 = new OutputArc("o20_t19_p4",p4,t19, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o27_t5_p24 = new OutputArc("o27_t5_p24",p24,t5, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o36_t34_p15 = new OutputArc("o36_t34_p15",p15,t34, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o23_t18_p1 = new OutputArc("o23_t18_p1",p1,t18, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o31_t6_p30 = new OutputArc("o31_t6_p30",p30,t6, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o17_t14_p15 = new OutputArc("o17_t14_p15",p15,t14, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };

  /** Class SHEERER_SINGLE_CYCLE constructor. */
  public SHEERER_SINGLE_CYCLE() {
     setId("n1");
     setLabel("SHEERER_SINGLE_CYCLE");
     setImportText("import java.util.Collections;\nimport java.util.stream.Stream;\nimport java.util.Arrays;\nimport java.util.Collection;\nimport java.util.List;\nimport java.util.stream.Collectors;");
     p15.setLabel("pe");
     addPlace(p15);
     p21.setLabel("pi");
     addPlace(p21);
     p24.setLabel("p24");
     addPlace(p24);
     p1.setLabel("Phase 1: Location increases");
     addPlace(p1);
     p2.setLabel("Phase 2: Location remains constant");
     addPlace(p2);
     p3.setLabel("Phase 3: Location decreases");
     addPlace(p3);
     p4.setLabel("Phase 4: Location highly increases");
     addPlace(p4);
     p30.setLabel("p30");
     addPlace(p30);
     p35.setLabel("p35");
     addPlace(p35);
     t14.setLabel("Phase 4 [end]");
     t14.setTimeScope(Range.closed(0L,10000L));
     t14.setGuardCondition(new VariableIncreasingTSG("Location in longwall", LifecycleStage.START).getComplementary());
     addTransition(t14);
     t18.setLabel("Phase 1 [start]");
     t18.setTimeScope(Range.closed(0L,10000L));
     t18.setGuardCondition(new VariableIncreasingTSG("Location in longwall", LifecycleStage.START));
     addTransition(t18);
     t19.setLabel("Phase 4 [start]");
     t19.setTimeScope(Range.closed(0L,5000L));
     t19.setGuardCondition(new ANDTSG(
                     new VariableIncreasingTSG("Location in longwall", LifecycleStage.START),
                     new GreaterThanTSG("Location in longwall", 40.0, true, LifecycleStage.START)
             ));
     addTransition(t19);
     t25.setLabel("Phase 2 [start]");
     t25.setTimeScope(Range.closed(0L,10000L));
     t25.setGuardCondition(new VariableConstantTSG("Location in longwall", LifecycleStage.START));
     addTransition(t25);
     t5.setLabel("Phase 1 [end]");
     t5.setTimeScope(Range.closed(0L,10000L));
     t5.setGuardCondition(new ANDTSG(
                                        Arrays.asList(
                                            new VariableIncreasingTSG("Location in longwall", LifecycleStage.END).getComplementary(),
                                            new GreaterThanTSG("Location in longwall", 30.0, false),
                                            new LessThanTSG("Location in longwall", 40.0, false)
                                        )
                                ));
     addTransition(t5);
     t6.setLabel("Phase 2 [end]");
     t6.setTimeScope(Range.closed(0L,10000L));
     t6.setGuardCondition(new VariableConstantTSG("Location in longwall").getComplementary());
     addTransition(t6);
     t7.setLabel("Phase 3 [end]");
     t7.setTimeScope(Range.closed(0L,10000L));
     t7.setGuardCondition(new VariableDecreasingTSG("Location in longwall", LifecycleStage.END).getComplementary());
     addTransition(t7);
     t32.setLabel("Phase 3 [start]");
     t32.setTimeScope(Range.closed(0L,10000L));
     t32.setGuardCondition(new VariableDecreasingTSG("Location in longwall", LifecycleStage.START));
     addTransition(t32);
     t34.setLabel("Phase 4 not present");
     t34.setTimeScope(Range.closed(0L,5000L));
     t34.setGuardCondition(new VariableIncreasingTSG("Location in longwall").getComplementary());
     addTransition(t34);
     i12_p3_t7.setEvaluateText("getTokenSet().size()>0");
     i12_p3_t7.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i12_p3_t7);
     i33_p30_t32.setEvaluateText("getTokenSet().size()>0");
     i33_p30_t32.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i33_p30_t32);
     i28_p24_t25.setEvaluateText("getTokenSet().size()>0");
     i28_p24_t25.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i28_p24_t25);
     i10_p2_t6.setEvaluateText("getTokenSet().size()>0");
     i10_p2_t6.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i10_p2_t6);
     i35_p35_t34.setEvaluateText("getTokenSet().size()>0");
     i35_p35_t34.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i35_p35_t34);
     i22_p21_t18.setEvaluateText("getTokenSet().size()>0");
     i22_p21_t18.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i22_p21_t18);
     i26_p1_t5.setEvaluateText("getTokenSet().size()>0");
     i26_p1_t5.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i26_p1_t5);
     i37_p35_t19.setEvaluateText("getTokenSet().size()>0");
     i37_p35_t19.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i37_p35_t19);
     i16_p4_t14.setEvaluateText("getTokenSet().size()>0");
     i16_p4_t14.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i16_p4_t14);
     addOutputArc(o29_t25_p2);
     addOutputArc(o36_t7_p35);
     addOutputArc(o34_t32_p3);
     addOutputArc(o20_t19_p4);
     addOutputArc(o27_t5_p24);
     addOutputArc(o36_t34_p15);
     addOutputArc(o23_t18_p1);
     addOutputArc(o31_t6_p30);
     addOutputArc(o17_t14_p15);
  }

public void configure(Toml cfg) {super.configure(cfg);}

}
