package SAVIER_integration.OP_models;

/* This is an autogenerated PetriNet Java file. */
import org.uam.aida.tscc.SAVIER_integration.tsg.SAVIERSupervisions;
import org.uam.aida.tscc.SAVIER_integration.tsg.SAVIERChecks;
import org.uam.aida.tscc.SAVIER_integration.tsg.SAVIERActions;
import org.uam.aida.tscc.business.*;
import org.uam.aida.tscc.APFE.TSWFnet.TSWFNet;
import org.uam.aida.tscc.APFE.OPResponse;
import org.uam.aida.tscc.APFE.WFnet.TokenEvaluator;
import java.util.Collections;
import java.util.stream.Stream;
import static org.uam.aida.tscc.APFE.utils.Maps.entriesToMap;
import static org.uam.aida.tscc.APFE.utils.Maps.entry;
public class APDL_FAIL extends TSWFNet {

  /** Custom declarations. */

  /** Places declaration. */
  private Place p89 = new Place("p89");
  private Place p90 = new Place("p90");
  private Place p12 = new Place("p12");
  private Place p11 = new Place("p11");
  private Place p14 = new Place("p14");
  private Place p13 = new Place("p13");
  private Place p15 = new Place("p15");
  private Place p116 = new Place("p116");
  private Place p119 = new Place("p119");
  private Place p106 = new Place("p106");
  private Place p26 = new Place("p26");
  private Place p109 = new Place("p109");
  private Place p108 = new Place("p108");
  private Place p1 = new Place("p1");
  private Place p7 = new Place("p7");
  private Place p45 = new Place("p45");
  private Place p124 = new Place("p124");
  private Place p44 = new Place("p44");
  private Place p47 = new Place("p47");
  private Place p46 = new Place("p46");
  private Place p49 = new Place("p49");
  private Place p48 = new Place("p48");

  /** Transitions declaration. */
  private Transition t122 = new Transition("t122","return ANDJoinGuard(this);","currentCase = ANDJoinWinner") {
         public boolean evaluate(){
                 return ANDJoinGuard(this);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = ANDJoinWinner);
         }
  };
  private Transition t121 = new Transition("t121","return (\n!evaluateInputTokens(this,new TokenEvaluator(){\npublic boolean evaluate(Token token) {\nreturn (\nSAVIERSupervisions.UAVAbortsTakeOff(\n(AlertResponse) token.getObject(),\ntoken.getTimestamp(),\nnull\n))!=null;\n}\n})\n);","currentCase = new Token(\ncurrentCase.getObject(),\n((AlertResponse) currentCase.getObject()).getAlert().getEndTime()\n)") {
         public boolean evaluate(){
                 return (
!evaluateInputTokens(this,new TokenEvaluator(){
public boolean evaluate(Token token) {
return (
SAVIERSupervisions.UAVAbortsTakeOff((OPResponse) token.getObject(),
token.getTimestamp(),
null
))!=null;
}
            })
);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(
currentCase.getObject(),
((OPResponse) currentCase.getObject()).getOPTriggering().getEndTime()
));
         }
  };
  private Transition t123 = new Transition("t123","return (\nevaluateInputTokens(this,new TokenEvaluator(){\npublic boolean evaluate(Token token) {\nreturn (\ngetActionTriggerTimestamp(\n(AlertResponse) token.getObject(),\ntoken.getTimestamp(),\nnull,\nnull,\nSAVIERActions::changeToGPDLOmnidirectAntenna\n))!=null;\n}\n})\n);","currentCase = new Token(\ncurrentCase.getObject(),\nSAVIERActions.changeToGPDLOmnidirectAntenna(\n(AlertResponse) currentCase.getObject(),\ncurrentCase.getTimestamp(),\nnull,\nnull)\n)") {
         public boolean evaluate(){
                 return (
evaluateInputTokens(this,new TokenEvaluator(){
public boolean evaluate(Token token) {
return (
getActionTriggerTimestamp((OPResponse) token.getObject(),
token.getTimestamp(),
null,
null,
SAVIERActions::changeToGPDLOmnidirectAntenna
))!=null;
}
            })
);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(
currentCase.getObject(),
SAVIERActions.changeToGPDLOmnidirectAntenna((OPResponse) currentCase.getObject(),
currentCase.getTimestamp(),
null,
null)
));
         }
  };
  private Transition t115 = new Transition("t115","return (\nevaluateInputTokens(this,new TokenEvaluator(){\npublic boolean evaluate(Token token) {\nreturn (\ngetActionTriggerTimestamp(\n(AlertResponse) token.getObject(),\ntoken.getTimestamp(),\nnull,\nCollections.unmodifiableMap(Stream.of(entry(\"mode\", 19)).collect(entriesToMap())),\nSAVIERActions::vehicleOperatingModeCommand\n))!=null;\n}\n})\n);","currentCase = new Token(\ncurrentCase.getObject(),\nSAVIERActions.vehicleOperatingModeCommand(\n(AlertResponse) currentCase.getObject(),\ncurrentCase.getTimestamp(),\nnull,\nCollections.unmodifiableMap(Stream.of(entry(\"mode\", 19)).collect(entriesToMap()))\n))") {
         public boolean evaluate(){
                 return (
evaluateInputTokens(this,new TokenEvaluator(){
public boolean evaluate(Token token) {
return (
getActionTriggerTimestamp((OPResponse) token.getObject(),
token.getTimestamp(),
null,
Collections.unmodifiableMap(Stream.of(entry("mode", 19)).collect(entriesToMap())),
SAVIERActions::vehicleOperatingModeCommand
))!=null;
}
            })
);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(
currentCase.getObject(),
SAVIERActions.vehicleOperatingModeCommand((OPResponse) currentCase.getObject(),
currentCase.getTimestamp(),
null,
Collections.unmodifiableMap(Stream.of(entry("mode", 19)).collect(entriesToMap()))
)));
         }
  };
  private Transition t114 = new Transition("t114","return (\nevaluateInputTokens(this,new TokenEvaluator(){\npublic boolean evaluate(Token token) {\nreturn (\ngetActionTriggerTimestamp(\n(AlertResponse) token.getObject(),\ntoken.getTimestamp(),\nnull,\nCollections.unmodifiableMap(Stream.of(entry(\"mode\", 54)).collect(entriesToMap())),\nSAVIERActions::vehicleOperatingModeCommand\n))!=null;\n}\n})\n);","currentCase = new Token(\ncurrentCase.getObject(),\nSAVIERActions.vehicleOperatingModeCommand(\n(AlertResponse) currentCase.getObject(),\ncurrentCase.getTimestamp(),\nnull,\nCollections.unmodifiableMap(Stream.of(entry(\"mode\", 54)).collect(entriesToMap()))\n))") {
         public boolean evaluate(){
                 return (
evaluateInputTokens(this,new TokenEvaluator(){
public boolean evaluate(Token token) {
return (
getActionTriggerTimestamp((OPResponse) token.getObject(),
token.getTimestamp(),
null,
Collections.unmodifiableMap(Stream.of(entry("mode", 54)).collect(entriesToMap())),
SAVIERActions::vehicleOperatingModeCommand
))!=null;
}
            })
);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(
currentCase.getObject(),
SAVIERActions.vehicleOperatingModeCommand((OPResponse) currentCase.getObject(),
currentCase.getTimestamp(),
null,
Collections.unmodifiableMap(Stream.of(entry("mode", 54)).collect(entriesToMap()))
)));
         }
  };
  private Transition t107 = new Transition("t107","return true;","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return true;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t5 = new Transition("t5","return SAVIERChecks.isFlightPhaseTakeOffRunActionsBeforeVROT(\n(AlertResponse) getTokenSet().get(0).getObject(), \ngetTokenSet().get(0).getTimestamp()\n);","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return SAVIERChecks.isFlightPhaseTakeOffRunActionsBeforeVROT((OPResponse) getTokenSet().get(0).getObject(), 
getTokenSet().get(0).getTimestamp()
);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t6 = new Transition("t6","return !SAVIERChecks.isFlightPhaseTakeOffRunActionsBeforeVROT(\n(AlertResponse) getTokenSet().get(0).getObject(), \ngetTokenSet().get(0).getTimestamp()\n);","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return !SAVIERChecks.isFlightPhaseTakeOffRunActionsBeforeVROT((OPResponse) getTokenSet().get(0).getObject(), 
getTokenSet().get(0).getTimestamp()
);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t74 = new Transition("t74","return ANDJoinGuard(this);","currentCase = ANDJoinWinner") {
         public boolean evaluate(){
                 return ANDJoinGuard(this);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = ANDJoinWinner);
         }
  };
  private Transition t75 = new Transition("t75","return ANDJoinGuard(this);","currentCase = ANDJoinWinner") {
         public boolean evaluate(){
                 return ANDJoinGuard(this);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = ANDJoinWinner);
         }
  };
  private Transition t92 = new Transition("t92","return (\nevaluateInputTokens(this,new TokenEvaluator(){\npublic boolean evaluate(Token token) {\nreturn (\nSAVIERSupervisions.UAVAbortsTakeOff(\n(AlertResponse) token.getObject(),\ntoken.getTimestamp(),\nnull\n))!=null;\n}\n})\n);","currentCase = new Token(\ncurrentCase.getObject(),\nSAVIERSupervisions.UAVAbortsTakeOff(\n(AlertResponse) currentCase.getObject(),\ncurrentCase.getTimestamp(),\nnull)\n)") {
         public boolean evaluate(){
                 return (
evaluateInputTokens(this,new TokenEvaluator(){
public boolean evaluate(Token token) {
return (
SAVIERSupervisions.UAVAbortsTakeOff((OPResponse) token.getObject(),
token.getTimestamp(),
null
))!=null;
}
            })
);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(
currentCase.getObject(),
SAVIERSupervisions.UAVAbortsTakeOff((OPResponse) currentCase.getObject(),
currentCase.getTimestamp(),
null)
));
         }
  };
  private Transition t16 = new Transition("t16","return !SAVIERChecks.PDLUPshow0InCoverageRedColor(\n(AlertResponse) getTokenSet().get(0).getObject(), \ngetTokenSet().get(0).getTimestamp()\n);","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return !SAVIERChecks.PDLUPshow0InCoverageRedColor((OPResponse) getTokenSet().get(0).getObject(), 
getTokenSet().get(0).getTimestamp()
);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t18 = new Transition("t18","return SAVIERChecks.PDLStatusIsFail(\n(AlertResponse) getTokenSet().get(0).getObject(), \ngetTokenSet().get(0).getTimestamp()\n);","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return SAVIERChecks.PDLStatusIsFail((OPResponse) getTokenSet().get(0).getObject(), 
getTokenSet().get(0).getTimestamp()
);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t17 = new Transition("t17","return SAVIERChecks.PDLUPshow0InCoverageRedColor(\n(AlertResponse) getTokenSet().get(0).getObject(), \ngetTokenSet().get(0).getTimestamp()\n);","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return SAVIERChecks.PDLUPshow0InCoverageRedColor((OPResponse) getTokenSet().get(0).getObject(), 
getTokenSet().get(0).getTimestamp()
);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t19 = new Transition("t19","return !SAVIERChecks.PDLStatusIsFail(\n(AlertResponse) getTokenSet().get(0).getObject(), \ngetTokenSet().get(0).getTimestamp()\n);","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return !SAVIERChecks.PDLStatusIsFail((OPResponse) getTokenSet().get(0).getObject(), 
getTokenSet().get(0).getTimestamp()
);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t21 = new Transition("t21","return SAVIERChecks.GOStatusIsNOGO(\n(AlertResponse) getTokenSet().get(0).getObject(), \ngetTokenSet().get(0).getTimestamp()\n);","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return SAVIERChecks.GOStatusIsNOGO((OPResponse) getTokenSet().get(0).getObject(), 
getTokenSet().get(0).getTimestamp()
);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t20 = new Transition("t20","return !SAVIERChecks.GOStatusIsNOGO(\n(AlertResponse) getTokenSet().get(0).getObject(), \ngetTokenSet().get(0).getTimestamp()\n);","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return !SAVIERChecks.GOStatusIsNOGO((OPResponse) getTokenSet().get(0).getObject(), 
getTokenSet().get(0).getTimestamp()
);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t23 = new Transition("t23","return SAVIERChecks.flightModeIsTakeOffArmed(\n(AlertResponse) getTokenSet().get(0).getObject(), \ngetTokenSet().get(0).getTimestamp()\n);","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return SAVIERChecks.flightModeIsTakeOffArmed((OPResponse) getTokenSet().get(0).getObject(), 
getTokenSet().get(0).getTimestamp()
);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t22 = new Transition("t22","return !SAVIERChecks.flightModeIsTakeOffArmed(\n(AlertResponse) getTokenSet().get(0).getObject(), \ngetTokenSet().get(0).getTimestamp()\n);","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return !SAVIERChecks.flightModeIsTakeOffArmed((OPResponse) getTokenSet().get(0).getObject(), 
getTokenSet().get(0).getTimestamp()
);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t25 = new Transition("t25","return SAVIERChecks.PDLAirAntennaIsDisplayedInRed(\n(AlertResponse) getTokenSet().get(0).getObject(), \ngetTokenSet().get(0).getTimestamp()\n);","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return SAVIERChecks.PDLAirAntennaIsDisplayedInRed((OPResponse) getTokenSet().get(0).getObject(), 
getTokenSet().get(0).getTimestamp()
);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t24 = new Transition("t24","return !SAVIERChecks.PDLAirAntennaIsDisplayedInRed(\n(AlertResponse) getTokenSet().get(0).getObject(), \ngetTokenSet().get(0).getTimestamp()\n);","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return !SAVIERChecks.PDLAirAntennaIsDisplayedInRed((OPResponse) getTokenSet().get(0).getObject(), 
getTokenSet().get(0).getTimestamp()
);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t27 = new Transition("t27","return !SAVIERChecks.GOStatusIsNOGO(\n(AlertResponse) getTokenSet().get(0).getObject(), \ngetTokenSet().get(0).getTimestamp()\n);","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return !SAVIERChecks.GOStatusIsNOGO((OPResponse) getTokenSet().get(0).getObject(), 
getTokenSet().get(0).getTimestamp()
);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t28 = new Transition("t28","return SAVIERChecks.GOStatusIsNOGO(\n(AlertResponse) getTokenSet().get(0).getObject(), \ngetTokenSet().get(0).getTimestamp()\n);","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return SAVIERChecks.GOStatusIsNOGO((OPResponse) getTokenSet().get(0).getObject(), 
getTokenSet().get(0).getTimestamp()
);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t101 = new Transition("t101","return (\nevaluateInputTokens(this,new TokenEvaluator(){\npublic boolean evaluate(Token token) {\nreturn (\ngetActionTriggerTimestamp(\n(AlertResponse) token.getObject(),\ntoken.getTimestamp(),\nnull,\nCollections.unmodifiableMap(Stream.of(entry(\"waypointNumber\", 4)).collect(entriesToMap())),\nSAVIERActions::commandWaypoint\n))!=null;\n}\n})\n);","currentCase = new Token(\ncurrentCase.getObject(),\nSAVIERActions.commandWaypoint(\n(AlertResponse) currentCase.getObject(),\ncurrentCase.getTimestamp(),\nnull,\nCollections.unmodifiableMap(Stream.of(entry(\"waypointNumber\", 4)).collect(entriesToMap()))\n))") {
         public boolean evaluate(){
                 return (
evaluateInputTokens(this,new TokenEvaluator(){
public boolean evaluate(Token token) {
return (
getActionTriggerTimestamp((OPResponse) token.getObject(),
token.getTimestamp(),
null,
Collections.unmodifiableMap(Stream.of(entry("waypointNumber", 4)).collect(entriesToMap())),
SAVIERActions::commandWaypoint
))!=null;
}
            })
);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(
currentCase.getObject(),
SAVIERActions.commandWaypoint((OPResponse) currentCase.getObject(),
currentCase.getTimestamp(),
null,
Collections.unmodifiableMap(Stream.of(entry("waypointNumber", 4)).collect(entriesToMap()))
)));
         }
  };

  /** Input Arcs declaration. */
  private InputArc i80_p47_t74 = new InputArc("i80_p47_t74",p47,t74, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i84_p45_t75 = new InputArc("i84_p45_t75",p45,t75, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i123_p124_t122 = new InputArc("i123_p124_t122",p124,t122, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i120_p109_t123 = new InputArc("i120_p109_t123",p109,t123, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i8_p1_t5 = new InputArc("i8_p1_t5",p1,t5, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i33_p13_t20 = new InputArc("i33_p13_t20",p13,t20, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i119_p116_t115 = new InputArc("i119_p116_t115",p116,t115, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i81_p48_t74 = new InputArc("i81_p48_t74",p48,t74, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i76_p44_t74 = new InputArc("i76_p44_t74",p44,t74, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i40_p26_t27 = new InputArc("i40_p26_t27",p26,t27, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i31_p12_t19 = new InputArc("i31_p12_t19",p12,t19, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i95_p90_t92 = new InputArc("i95_p90_t92",p90,t92, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i115_p89_t101 = new InputArc("i115_p89_t101",p89,t101, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i122_p90_t121 = new InputArc("i122_p90_t121",p90,t121, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i124_p119_t122 = new InputArc("i124_p119_t122",p119,t122, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i117_p108_t114 = new InputArc("i117_p108_t114",p108,t114, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i9_p1_t6 = new InputArc("i9_p1_t6",p1,t6, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i39_p26_t28 = new InputArc("i39_p26_t28",p26,t28, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i32_p12_t18 = new InputArc("i32_p12_t18",p12,t18, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i36_p14_t23 = new InputArc("i36_p14_t23",p14,t23, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i111_p106_t107 = new InputArc("i111_p106_t107",p106,t107, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i77_p45_t74 = new InputArc("i77_p45_t74",p45,t74, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i87_p48_t75 = new InputArc("i87_p48_t75",p48,t75, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i79_p46_t74 = new InputArc("i79_p46_t74",p46,t74, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i29_p11_t16 = new InputArc("i29_p11_t16",p11,t16, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i30_p11_t17 = new InputArc("i30_p11_t17",p11,t17, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i38_p15_t25 = new InputArc("i38_p15_t25",p15,t25, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i35_p14_t22 = new InputArc("i35_p14_t22",p14,t22, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i88_p49_t75 = new InputArc("i88_p49_t75",p49,t75, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i83_p44_t75 = new InputArc("i83_p44_t75",p44,t75, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i34_p13_t21 = new InputArc("i34_p13_t21",p13,t21, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i37_p15_t24 = new InputArc("i37_p15_t24",p15,t24, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };

  /** Output Arcs declaration. */
  private OutputArc o126_t92_p7 = new OutputArc("o126_t92_p7",p7,t92, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o73_t28_p7 = new OutputArc("o73_t28_p7",p7,t28, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o66_t16_p7 = new OutputArc("o66_t16_p7",p7,t16, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o54_t23_p47 = new OutputArc("o54_t23_p47",p47,t23, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o110_t101_p106 = new OutputArc("o110_t101_p106",p106,t101, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o127_t115_p124 = new OutputArc("o127_t115_p124",p124,t115, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o121_t123_p119 = new OutputArc("o121_t123_p119",p119,t123, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o69_t19_p7 = new OutputArc("o69_t19_p7",p7,t19, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o50_t17_p44 = new OutputArc("o50_t17_p44",p44,t17, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o118_t114_p116 = new OutputArc("o118_t114_p116",p116,t114, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o111_t6_p11 = new OutputArc("o111_t6_p11",p11,t6, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o65_t6_p26 = new OutputArc("o65_t6_p26",p26,t6, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o71_t22_p7 = new OutputArc("o71_t22_p7",p7,t22, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o112_t107_p109 = new OutputArc("o112_t107_p109",p109,t107, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o51_t18_p45 = new OutputArc("o51_t18_p45",p45,t18, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o124_t74_p90 = new OutputArc("o124_t74_p90",p90,t74, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o125_t122_p7 = new OutputArc("o125_t122_p7",p7,t122, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o72_t24_p7 = new OutputArc("o72_t24_p7",p7,t24, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o125_t6_p15 = new OutputArc("o125_t6_p15",p15,t6, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o57_t5_p12 = new OutputArc("o57_t5_p12",p12,t5, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o59_t5_p14 = new OutputArc("o59_t5_p14",p14,t5, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o58_t5_p13 = new OutputArc("o58_t5_p13",p13,t5, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o55_t25_p48 = new OutputArc("o55_t25_p48",p48,t25, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o123_t75_p89 = new OutputArc("o123_t75_p89",p89,t75, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o56_t27_p49 = new OutputArc("o56_t27_p49",p49,t27, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o52_t21_p46 = new OutputArc("o52_t21_p46",p46,t21, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o60_t5_p15 = new OutputArc("o60_t5_p15",p15,t5, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o42_t5_p11 = new OutputArc("o42_t5_p11",p11,t5, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o113_t6_p12 = new OutputArc("o113_t6_p12",p12,t6, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o125_t121_p89 = new OutputArc("o125_t121_p89",p89,t121, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o111_t107_p108 = new OutputArc("o111_t107_p108",p108,t107, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o70_t20_p7 = new OutputArc("o70_t20_p7",p7,t20, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };

  /** Class APDL_FAIL constructor. */
  public APDL_FAIL() {
     setId("n0");
     setLabel("APDL_FAIL");
     setImportText("import MBPFE.AlertResponse;\nimport MBPFE.queries.SAVIER.*;\nimport MBPFE.workflow.TokenEvaluator;\nimport java.util.Collections;\nimport java.util.stream.Stream;\nimport static MBPFE.utils.Maps.entriesToMap;\nimport static MBPFE.utils.Maps.entry;");
     p89.setLabel("p89");
     addPlace(p89);
     p90.setLabel("p90");
     addPlace(p90);
     p12.setLabel("p12");
     addPlace(p12);
     p11.setLabel("p11");
     addPlace(p11);
     p14.setLabel("p14");
     addPlace(p14);
     p13.setLabel("p13");
     addPlace(p13);
     p15.setLabel("p15");
     addPlace(p15);
     p116.setLabel("p116");
     addPlace(p116);
     p119.setLabel("p119");
     addPlace(p119);
     p106.setLabel("p106");
     addPlace(p106);
     p26.setLabel("p26");
     addPlace(p26);
     p109.setLabel("p109");
     addPlace(p109);
     p108.setLabel("p108");
     addPlace(p108);
     p1.setLabel("input");
     addPlace(p1);
     p7.setLabel("output");
     addPlace(p7);
     p45.setLabel("p45");
     addPlace(p45);
     p124.setLabel("p124");
     addPlace(p124);
     p44.setLabel("p44");
     addPlace(p44);
     p47.setLabel("p47");
     addPlace(p47);
     p46.setLabel("p46");
     addPlace(p46);
     p49.setLabel("p49");
     addPlace(p49);
     p48.setLabel("p48");
     addPlace(p48);
     t122.setLabel("AND_JOIN");
     addTransition(t122);
     t121.setLabel("SUPERVISION:A/V Aborts Take Off:NOT FULFILLED");
     addTransition(t121);
     t123.setLabel("ACTION:Change to G-PDL Omnidirect");
     addTransition(t123);
     t115.setLabel("ACTION:LANDING");
     addTransition(t115);
     t114.setLabel("ACTION:ARMED CONVENTIONAL LANDING");
     addTransition(t114);
     t107.setLabel("AND SPLIT");
     addTransition(t107);
     t5.setLabel("CHECK:Phase=TakeOffRunActionsBeforeVROT:FULFILLED");
     addTransition(t5);
     t6.setLabel("CHECK:Phase=ActionsInAnyOtherPhase:FULFILLED");
     addTransition(t6);
     t74.setLabel("PassChecks");
     addTransition(t74);
     t75.setLabel("PassChecks");
     addTransition(t75);
     t92.setLabel("SUPERVISION:A/V Aborts Take Off:FULFILLED");
     addTransition(t92);
     t16.setLabel("CHECK:HMP:PDL_UP=0%:NOT FULFILLED");
     addTransition(t16);
     t18.setLabel("CHECK:HMP:PDL_Status=FAIL:FULFILLED");
     addTransition(t18);
     t17.setLabel("CHECK:HMP:PDL_UP=0%:FULFILLED");
     addTransition(t17);
     t19.setLabel("CHECK:HMP:PDL_Status=FAIL:NOT FULFILLED");
     addTransition(t19);
     t21.setLabel("CHECK:HMP:GO_STATUS=NO-GO:FULFILLED");
     addTransition(t21);
     t20.setLabel("CHECK:HMP:GO_STATUS=NO-GO:NOT FULFILLED");
     addTransition(t20);
     t23.setLabel("CHECK:HMP:FLIGHT MODE=TAKE OFF ARMED:FULFILLED");
     addTransition(t23);
     t22.setLabel("CHECK:HMP:FLIGHT MODE=TAKE OFF ARMED:NOT FULFILLED");
     addTransition(t22);
     t25.setLabel("CHECK:HMP:PDL Air antenna is displaed in red:FULFILLED");
     addTransition(t25);
     t24.setLabel("CHECK:HMP:PDL Air antenna is displayed in red:NOT FULFILLED");
     addTransition(t24);
     t27.setLabel("CHECK:HMP:GO STATUS is GO:FULFILLED");
     addTransition(t27);
     t28.setLabel("CHECK:HMP:GO STATUS is GO:NOT FULFILLED");
     addTransition(t28);
     t101.setLabel("ACTION:GO-WP(IAF)");
     addTransition(t101);
     i80_p47_t74.setEvaluateText("getTokenSet().size()>0");
     i80_p47_t74.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i80_p47_t74);
     i84_p45_t75.setEvaluateText("getTokenSet().size()>0");
     i84_p45_t75.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i84_p45_t75);
     i123_p124_t122.setEvaluateText("getTokenSet().size()>0");
     i123_p124_t122.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i123_p124_t122);
     i120_p109_t123.setEvaluateText("getTokenSet().size()>0");
     i120_p109_t123.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i120_p109_t123);
     i8_p1_t5.setEvaluateText("getTokenSet().size()>0");
     i8_p1_t5.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i8_p1_t5);
     i33_p13_t20.setEvaluateText("getTokenSet().size()>0");
     i33_p13_t20.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i33_p13_t20);
     i119_p116_t115.setEvaluateText("getTokenSet().size()>0");
     i119_p116_t115.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i119_p116_t115);
     i81_p48_t74.setEvaluateText("getTokenSet().size()>0");
     i81_p48_t74.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i81_p48_t74);
     i76_p44_t74.setEvaluateText("getTokenSet().size()>0");
     i76_p44_t74.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i76_p44_t74);
     i40_p26_t27.setEvaluateText("getTokenSet().size()>0");
     i40_p26_t27.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i40_p26_t27);
     i31_p12_t19.setEvaluateText("getTokenSet().size()>0");
     i31_p12_t19.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i31_p12_t19);
     i95_p90_t92.setEvaluateText("getTokenSet().size()>0");
     i95_p90_t92.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i95_p90_t92);
     i115_p89_t101.setEvaluateText("getTokenSet().size()>0");
     i115_p89_t101.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i115_p89_t101);
     i122_p90_t121.setEvaluateText("getTokenSet().size()>0");
     i122_p90_t121.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i122_p90_t121);
     i124_p119_t122.setEvaluateText("getTokenSet().size()>0");
     i124_p119_t122.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i124_p119_t122);
     i117_p108_t114.setEvaluateText("getTokenSet().size()>0");
     i117_p108_t114.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i117_p108_t114);
     i9_p1_t6.setEvaluateText("getTokenSet().size()>0");
     i9_p1_t6.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i9_p1_t6);
     i39_p26_t28.setEvaluateText("getTokenSet().size()>0");
     i39_p26_t28.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i39_p26_t28);
     i32_p12_t18.setEvaluateText("getTokenSet().size()>0");
     i32_p12_t18.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i32_p12_t18);
     i36_p14_t23.setEvaluateText("getTokenSet().size()>0");
     i36_p14_t23.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i36_p14_t23);
     i111_p106_t107.setEvaluateText("getTokenSet().size()>0");
     i111_p106_t107.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i111_p106_t107);
     i77_p45_t74.setEvaluateText("getTokenSet().size()>0");
     i77_p45_t74.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i77_p45_t74);
     i87_p48_t75.setEvaluateText("getTokenSet().size()>0");
     i87_p48_t75.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i87_p48_t75);
     i79_p46_t74.setEvaluateText("getTokenSet().size()>0");
     i79_p46_t74.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i79_p46_t74);
     i29_p11_t16.setEvaluateText("getTokenSet().size()>0");
     i29_p11_t16.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i29_p11_t16);
     i30_p11_t17.setEvaluateText("getTokenSet().size()>0");
     i30_p11_t17.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i30_p11_t17);
     i38_p15_t25.setEvaluateText("getTokenSet().size()>0");
     i38_p15_t25.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i38_p15_t25);
     i35_p14_t22.setEvaluateText("getTokenSet().size()>0");
     i35_p14_t22.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i35_p14_t22);
     i88_p49_t75.setEvaluateText("getTokenSet().size()>0");
     i88_p49_t75.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i88_p49_t75);
     i83_p44_t75.setEvaluateText("getTokenSet().size()>0");
     i83_p44_t75.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i83_p44_t75);
     i34_p13_t21.setEvaluateText("getTokenSet().size()>0");
     i34_p13_t21.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i34_p13_t21);
     i37_p15_t24.setEvaluateText("getTokenSet().size()>0");
     i37_p15_t24.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i37_p15_t24);
     addOutputArc(o126_t92_p7);
     addOutputArc(o73_t28_p7);
     addOutputArc(o66_t16_p7);
     addOutputArc(o54_t23_p47);
     addOutputArc(o110_t101_p106);
     addOutputArc(o127_t115_p124);
     addOutputArc(o121_t123_p119);
     addOutputArc(o69_t19_p7);
     addOutputArc(o50_t17_p44);
     addOutputArc(o118_t114_p116);
     addOutputArc(o111_t6_p11);
     addOutputArc(o65_t6_p26);
     addOutputArc(o71_t22_p7);
     addOutputArc(o112_t107_p109);
     addOutputArc(o51_t18_p45);
     addOutputArc(o124_t74_p90);
     addOutputArc(o125_t122_p7);
     addOutputArc(o72_t24_p7);
     addOutputArc(o125_t6_p15);
     addOutputArc(o57_t5_p12);
     addOutputArc(o59_t5_p14);
     addOutputArc(o58_t5_p13);
     addOutputArc(o55_t25_p48);
     addOutputArc(o123_t75_p89);
     addOutputArc(o56_t27_p49);
     addOutputArc(o52_t21_p46);
     addOutputArc(o60_t5_p15);
     addOutputArc(o42_t5_p11);
     addOutputArc(o113_t6_p12);
     addOutputArc(o125_t121_p89);
     addOutputArc(o111_t107_p108);
     addOutputArc(o70_t20_p7);
  }

}
