package SAVIER_integration.OP_models;

/* This is an autogenerated PetriNet Java file. */
import org.uam.aida.tscc.SAVIER_integration.tsg.SAVIERActions;
import org.uam.aida.tscc.SAVIER_integration.tsg.SAVIERTimedConditions;
import org.uam.aida.tscc.business.*;
import org.uam.aida.tscc.APFE.TSWFnet.TSWFNet;
import org.uam.aida.tscc.APFE.OPResponse;
import SAVIER_integration.SAVIERConstants;
import org.uam.aida.tscc.APFE.WFnet.TokenEvaluator;
import org.uam.aida.tscc.APFE.utils.Triple;
import java.util.Collections;
import java.util.stream.Stream;
import java.util.Arrays;
import static org.uam.aida.tscc.APFE.utils.Maps.entriesToMap;
import static org.uam.aida.tscc.APFE.utils.Maps.entry;
public class ENGINE_BAY_OVERHEATING extends TSWFNet {

  /** Custom declarations. */

  /** Places declaration. */
  private Place p0 = new Place("p0");
  private Place p4 = new Place("p4");
  private Place p9 = new Place("p9");
  private Place p13 = new Place("p13");
  private Place p17 = new Place("p17");
  private Place p22 = new Place("p22");
  private Place p26 = new Place("p26");

  /** Transitions declaration. */
  private Transition t12 = new Transition("t12","return (\nevaluateInputTokens(this,new TokenEvaluator(){\npublic boolean evaluate(Token token) {\nreturn (\ngetActionTriggerTimestamp(\n(AlertResponse) token.getObject(),\ntoken.getTimestamp(),\n((AlertResponse) token.getObject()).getAlert().getEndTime() + SAVIERConstants.EBO_EXTRA_RESPONSE_TIME,\nCollections.unmodifiableMap(Stream.of(entry(\"waypointNumber\", 4)).collect(entriesToMap())),\nSAVIERActions::commandWaypoint\n))!=null;\n}\n})\n);","currentCase = new Token(\ncurrentCase.getObject(),\nSAVIERActions.commandWaypoint(\n(AlertResponse) currentCase.getObject(),\ncurrentCase.getTimestamp(),\n((AlertResponse) currentCase.getObject()).getAlert().getEndTime() + SAVIERConstants.EBO_EXTRA_RESPONSE_TIME,\nCollections.unmodifiableMap(Stream.of(entry(\"waypointNumber\", 4)).collect(entriesToMap()))\n))") {
         public boolean evaluate(){
                 return (
evaluateInputTokens(this,new TokenEvaluator(){
public boolean evaluate(Token token) {
return (
getActionTriggerTimestamp((OPResponse) token.getObject(),
token.getTimestamp(),
((OPResponse) token.getObject()).getOPTriggering().getEndTime() + SAVIERConstants.EBO_EXTRA_RESPONSE_TIME,
Collections.unmodifiableMap(Stream.of(entry("waypointNumber", 4)).collect(entriesToMap())),
SAVIERActions::commandWaypoint
))!=null;
}
            })
);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(
currentCase.getObject(),
SAVIERActions.commandWaypoint((OPResponse) currentCase.getObject(),
currentCase.getTimestamp(),
((OPResponse) currentCase.getObject()).getOPTriggering().getEndTime() + SAVIERConstants.EBO_EXTRA_RESPONSE_TIME,
Collections.unmodifiableMap(Stream.of(entry("waypointNumber", 4)).collect(entriesToMap()))
)));
         }
  };
  private Transition t18 = new Transition("t18","return (\nevaluateInputTokens(this,new TokenEvaluator(){\npublic boolean evaluate(Token token) {\nreturn (\ngetActionTriggerTimestamp(\n(AlertResponse) token.getObject(),\ntoken.getTimestamp(),\n((AlertResponse) token.getObject()).getAlert().getEndTime() + SAVIERConstants.EBO_EXTRA_RESPONSE_TIME,\nCollections.unmodifiableMap(Stream.of(entry(\"mode\", 33)).collect(entriesToMap())),\nSAVIERActions::vehicleOperatingModeCommand\n))!=null;\n}\n})\n);","currentCase = new Token(\ncurrentCase.getObject(),\nSAVIERActions.vehicleOperatingModeCommand(\n(AlertResponse) currentCase.getObject(),\ncurrentCase.getTimestamp(),\n((AlertResponse) currentCase.getObject()).getAlert().getEndTime() + SAVIERConstants.EBO_EXTRA_RESPONSE_TIME,\nCollections.unmodifiableMap(Stream.of(entry(\"mode\", 33)).collect(entriesToMap()))\n))") {
         public boolean evaluate(){
                 return (
evaluateInputTokens(this,new TokenEvaluator(){
public boolean evaluate(Token token) {
return (
getActionTriggerTimestamp((OPResponse) token.getObject(),
token.getTimestamp(),
((OPResponse) token.getObject()).getOPTriggering().getEndTime() + SAVIERConstants.EBO_EXTRA_RESPONSE_TIME,
Collections.unmodifiableMap(Stream.of(entry("mode", 33)).collect(entriesToMap())),
SAVIERActions::vehicleOperatingModeCommand
))!=null;
}
            })
);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(
currentCase.getObject(),
SAVIERActions.vehicleOperatingModeCommand((OPResponse) currentCase.getObject(),
currentCase.getTimestamp(),
((OPResponse) currentCase.getObject()).getOPTriggering().getEndTime() + SAVIERConstants.EBO_EXTRA_RESPONSE_TIME,
Collections.unmodifiableMap(Stream.of(entry("mode", 33)).collect(entriesToMap()))
)));
         }
  };
  private Transition t21 = new Transition("t21","return (\nevaluateInputTokens(this,new TokenEvaluator(){\npublic boolean evaluate(Token token) {\nreturn (\ngetActionTriggerTimestamp(\n(AlertResponse) token.getObject(),\ntoken.getTimestamp(),\n((AlertResponse) token.getObject()).getAlert().getEndTime() + SAVIERConstants.EBO_EXTRA_RESPONSE_TIME,\nCollections.unmodifiableMap(Stream.of(entry(\"mode\", 54)).collect(entriesToMap())),\nSAVIERActions::vehicleOperatingModeCommand\n))!=null;\n}\n})\n);","currentCase = new Token(\ncurrentCase.getObject(),\nSAVIERActions.vehicleOperatingModeCommand(\n(AlertResponse) currentCase.getObject(),\ncurrentCase.getTimestamp(),\n((AlertResponse) currentCase.getObject()).getAlert().getEndTime() + SAVIERConstants.EBO_EXTRA_RESPONSE_TIME,\nCollections.unmodifiableMap(Stream.of(entry(\"mode\", 54)).collect(entriesToMap()))\n))") {
         public boolean evaluate(){
                 return (
evaluateInputTokens(this,new TokenEvaluator(){
public boolean evaluate(Token token) {
return (
getActionTriggerTimestamp((OPResponse) token.getObject(),
token.getTimestamp(),
((OPResponse) token.getObject()).getOPTriggering().getEndTime() + SAVIERConstants.EBO_EXTRA_RESPONSE_TIME,
Collections.unmodifiableMap(Stream.of(entry("mode", 54)).collect(entriesToMap())),
SAVIERActions::vehicleOperatingModeCommand
))!=null;
}
            })
);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(
currentCase.getObject(),
SAVIERActions.vehicleOperatingModeCommand((OPResponse) currentCase.getObject(),
currentCase.getTimestamp(),
((OPResponse) currentCase.getObject()).getOPTriggering().getEndTime() + SAVIERConstants.EBO_EXTRA_RESPONSE_TIME,
Collections.unmodifiableMap(Stream.of(entry("mode", 54)).collect(entriesToMap()))
)));
         }
  };
  private Transition t27 = new Transition("t27","return (\nevaluateInputTokens(this,new TokenEvaluator(){\npublic boolean evaluate(Token token) {\nreturn (\ngetActionTriggerTimestamp(\n(AlertResponse) token.getObject(),\ntoken.getTimestamp(),\n((AlertResponse) token.getObject()).getAlert().getEndTime() + SAVIERConstants.EBO_EXTRA_RESPONSE_TIME,\nCollections.unmodifiableMap(Stream.of(entry(\"mode\", 19)).collect(entriesToMap())),\nSAVIERActions::vehicleOperatingModeCommand\n))!=null;\n}\n})\n);","currentCase = new Token(\ncurrentCase.getObject(),\nSAVIERActions.vehicleOperatingModeCommand(\n(AlertResponse) currentCase.getObject(),\ncurrentCase.getTimestamp(),\n((AlertResponse) currentCase.getObject()).getAlert().getEndTime() + SAVIERConstants.EBO_EXTRA_RESPONSE_TIME,\nCollections.unmodifiableMap(Stream.of(entry(\"mode\", 19)).collect(entriesToMap()))\n))") {
         public boolean evaluate(){
                 return (
evaluateInputTokens(this,new TokenEvaluator(){
public boolean evaluate(Token token) {
return (
getActionTriggerTimestamp((OPResponse) token.getObject(),
token.getTimestamp(),
((OPResponse) token.getObject()).getOPTriggering().getEndTime() + SAVIERConstants.EBO_EXTRA_RESPONSE_TIME,
Collections.unmodifiableMap(Stream.of(entry("mode", 19)).collect(entriesToMap())),
SAVIERActions::vehicleOperatingModeCommand
))!=null;
}
            })
);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(
currentCase.getObject(),
SAVIERActions.vehicleOperatingModeCommand((OPResponse) currentCase.getObject(),
currentCase.getTimestamp(),
((OPResponse) currentCase.getObject()).getOPTriggering().getEndTime() + SAVIERConstants.EBO_EXTRA_RESPONSE_TIME,
Collections.unmodifiableMap(Stream.of(entry("mode", 19)).collect(entriesToMap()))
)));
         }
  };
  private Transition t1 = new Transition("t1","return (\nevaluateInputTokens(this,new TokenEvaluator(){\npublic boolean evaluate(Token token) {\nreturn (\ngetActionTriggerTimestamp(\n(AlertResponse) token.getObject(),\ntoken.getTimestamp(),\n((AlertResponse) token.getObject()).getAlert().getEndTime() + SAVIERConstants.EBO_EXTRA_RESPONSE_TIME,\nnull,\nSAVIERActions::modifyUAVAltitudeOrSpeed\n))!=null;\n}\n})\n);","currentCase = new Token(\ncurrentCase.getObject(),\nSAVIERActions.modifyUAVAltitudeOrSpeed(\n(AlertResponse) currentCase.getObject(),\ncurrentCase.getTimestamp(),\n((AlertResponse) currentCase.getObject()).getAlert().getEndTime() + SAVIERConstants.EBO_EXTRA_RESPONSE_TIME,\nnull\n))") {
         public boolean evaluate(){
                 return (
evaluateInputTokens(this,new TokenEvaluator(){
public boolean evaluate(Token token) {
return (
getActionTriggerTimestamp((OPResponse) token.getObject(),
token.getTimestamp(),
((OPResponse) token.getObject()).getOPTriggering().getEndTime() + SAVIERConstants.EBO_EXTRA_RESPONSE_TIME,
null,
SAVIERActions::modifyUAVAltitudeOrSpeed
))!=null;
}
            })
);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(
currentCase.getObject(),
SAVIERActions.modifyUAVAltitudeOrSpeed((OPResponse) currentCase.getObject(),
currentCase.getTimestamp(),
((OPResponse) currentCase.getObject()).getOPTriggering().getEndTime() + SAVIERConstants.EBO_EXTRA_RESPONSE_TIME,
null
)));
         }
  };
  private Transition t2 = new Transition("t2","return \n(\nSAVIERTimedConditions.verifyConditions(\n(AlertResponse) getTokenSet().get(0).getObject(), \ngetTokenSet().get(0).getTimestamp(),\ngetTokenSet().get(0).getTimestamp() + 300000L,\nCollections.unmodifiableMap(Stream.of(\nentry(\"55254\", Arrays.asList(new Triple(\"Engine_Bay_Temperature\",\"=\",3)))\n).collect(entriesToMap()))) != null\n);","currentCase = new Token(\ncurrentCase.getObject(),\nSAVIERTimedConditions.verifyConditions(\n(AlertResponse) currentCase.getObject(), \ncurrentCase.getTimestamp(),\ncurrentCase.getTimestamp() + 300000L,\nCollections.unmodifiableMap(Stream.of(\nentry(\"55254\", Arrays.asList(new Triple(\"Engine_Bay_Temperature\",\"=\",3)))\n).collect(entriesToMap()))\n))") {
         public boolean evaluate(){
                 return 
(
SAVIERTimedConditions.verifyConditions((OPResponse) getTokenSet().get(0).getObject(), 
getTokenSet().get(0).getTimestamp(),
getTokenSet().get(0).getTimestamp() + 300000L,
Collections.unmodifiableMap(Stream.of(
entry("55254", Arrays.asList(new Triple("Engine_Bay_Temperature","=",3)))
).collect(entriesToMap()))) != null
);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(
currentCase.getObject(),
SAVIERTimedConditions.verifyConditions((OPResponse) currentCase.getObject(), 
currentCase.getTimestamp(),
currentCase.getTimestamp() + 300000L,
Collections.unmodifiableMap(Stream.of(
entry("55254", Arrays.asList(new Triple("Engine_Bay_Temperature","=",3)))
).collect(entriesToMap()))
)));
         }
  };
  private Transition t3 = new Transition("t3","return \n!(\nSAVIERTimedConditions.verifyConditions(\n(AlertResponse) getTokenSet().get(0).getObject(), \ngetTokenSet().get(0).getTimestamp(),\ngetTokenSet().get(0).getTimestamp() + 300000L,\nCollections.unmodifiableMap(Stream.of(\nentry(\"55254\", Arrays.asList(new Triple(\"Engine_Bay_Temperature\",\"=\",3)))\n).collect(entriesToMap()))) != null\n);","currentCase = new Token(\ncurrentCase.getObject(),\ncurrentCase.getTimestamp() + 300000L\n)") {
         public boolean evaluate(){
                 return 
!(
SAVIERTimedConditions.verifyConditions((OPResponse) getTokenSet().get(0).getObject(), 
getTokenSet().get(0).getTimestamp(),
getTokenSet().get(0).getTimestamp() + 300000L,
Collections.unmodifiableMap(Stream.of(
entry("55254", Arrays.asList(new Triple("Engine_Bay_Temperature","=",3)))
).collect(entriesToMap()))) != null
);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(
currentCase.getObject(),
currentCase.getTimestamp() + 300000L
));
         }
  };

  /** Input Arcs declaration. */
  private InputArc i24_p22_t21 = new InputArc("i24_p22_t21",p22,t21, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i20_p17_t18 = new InputArc("i20_p17_t18",p17,t18, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i8_p4_t3 = new InputArc("i8_p4_t3",p4,t3, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i15_p13_t12 = new InputArc("i15_p13_t12",p13,t12, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i5_p0_t1 = new InputArc("i5_p0_t1",p0,t1, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i7_p4_t2 = new InputArc("i7_p4_t2",p4,t2, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i29_p26_t27 = new InputArc("i29_p26_t27",p26,t27, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };

  /** Output Arcs declaration. */
  private OutputArc o30_t27_p9 = new OutputArc("o30_t27_p9",p9,t27, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o28_t21_p26 = new OutputArc("o28_t21_p26",p26,t21, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o16_t3_p13 = new OutputArc("o16_t3_p13",p13,t3, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o19_t2_p17 = new OutputArc("o19_t2_p17",p17,t2, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o21_t18_p9 = new OutputArc("o21_t18_p9",p9,t18, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o23_t12_p22 = new OutputArc("o23_t12_p22",p22,t12, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o6_t1_p4 = new OutputArc("o6_t1_p4",p4,t1, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };

  /** Class ENGINE_BAY_OVERHEATING constructor. */
  public ENGINE_BAY_OVERHEATING() {
     setId("n0");
     setLabel("ENGINE_BAY_OVERHEATING");
     setImportText("import MBPFE.AlertResponse;\nimport MBPFE.Constants.SAVIERConstants;\nimport MBPFE.queries.SAVIER.*;\nimport MBPFE.workflow.TokenEvaluator;\nimport MBPFE.utils.Triple;\nimport java.util.Collections;\nimport java.util.stream.Stream;\nimport java.util.Arrays;\nimport static MBPFE.utils.Maps.entriesToMap;\nimport static MBPFE.utils.Maps.entry;");
     p0.setLabel("START (Step 1)");
     addPlace(p0);
     p4.setLabel("p4");
     addPlace(p4);
     p9.setLabel("END");
     addPlace(p9);
     p13.setLabel("Step 2.1");
     addPlace(p13);
     p17.setLabel("p17");
     addPlace(p17);
     p22.setLabel("Step 2.2");
     addPlace(p22);
     p26.setLabel("Step 2.3");
     addPlace(p26);
     t12.setLabel("ACTION:GO-WP(IAF)");
     addTransition(t12);
     t18.setLabel("ACTION:Resume Mission");
     addTransition(t18);
     t21.setLabel("ACTION:ARMED CONVENTIONAL LANDING");
     addTransition(t21);
     t27.setLabel("ACTION:LANDING");
     addTransition(t27);
     t1.setLabel("ACTION:Modify Altitude or Speed");
     addTransition(t1);
     t2.setLabel("SUPERVISION:Alert Disappears:FULFILLED");
     addTransition(t2);
     t3.setLabel("SUPERVISION:Alert Disappears:NOT FULFILLED");
     addTransition(t3);
     i24_p22_t21.setEvaluateText("getTokenSet().size()>0");
     i24_p22_t21.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i24_p22_t21);
     i20_p17_t18.setEvaluateText("getTokenSet().size()>0");
     i20_p17_t18.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i20_p17_t18);
     i8_p4_t3.setEvaluateText("getTokenSet().size()>0");
     i8_p4_t3.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i8_p4_t3);
     i15_p13_t12.setEvaluateText("getTokenSet().size()>0");
     i15_p13_t12.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i15_p13_t12);
     i5_p0_t1.setEvaluateText("getTokenSet().size()>0");
     i5_p0_t1.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i5_p0_t1);
     i7_p4_t2.setEvaluateText("getTokenSet().size()>0");
     i7_p4_t2.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i7_p4_t2);
     i29_p26_t27.setEvaluateText("getTokenSet().size()>0");
     i29_p26_t27.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i29_p26_t27);
     addOutputArc(o30_t27_p9);
     addOutputArc(o28_t21_p26);
     addOutputArc(o16_t3_p13);
     addOutputArc(o19_t2_p17);
     addOutputArc(o21_t18_p9);
     addOutputArc(o23_t12_p22);
     addOutputArc(o6_t1_p4);
  }

}
