package SAVIER_integration.OP_models;

/* This is an autogenerated PetriNet Java file. */
import org.uam.aida.tscc.SAVIER_integration.tsg.SAVIERInstantConditions;
import org.uam.aida.tscc.SAVIER_integration.tsg.SAVIERTimedConditions;
import org.uam.aida.tscc.SAVIER_integration.tsg.SAVIERQueriesUtils;
import org.uam.aida.tscc.business.*;
import org.uam.aida.tscc.APFE.TSWFnet.TSWFNet;
import org.uam.aida.tscc.APFE.OPResponse;
import SAVIER_integration.SAVIERConstants;
import org.uam.aida.tscc.APFE.WFnet.TokenEvaluator;
import org.uam.aida.tscc.APFE.utils.Triple;
import java.util.Collections;
import java.util.stream.Stream;
import java.util.Arrays;
import static org.uam.aida.tscc.APFE.utils.Maps.entriesToMap;
import static org.uam.aida.tscc.APFE.utils.Maps.entry;
public class NORMAL_TAKE_OFF_full extends TSWFNet {

  /** Custom declarations. */

  /** Places declaration. */
  private Place p160 = new Place("p160");
  private Place p159 = new Place("p159");
  private Place p153 = new Place("p153");
  private Place p147 = new Place("p147");
  private Place p182 = new Place("p182");
  private Place p185 = new Place("p185");
  private Place p179 = new Place("p179");
  private Place p173 = new Place("p173");
  private Place p172 = new Place("p172");
  private Place p18 = new Place("p18");
  private Place p19 = new Place("p19");
  private Place p193 = new Place("p193");
  private Place p192 = new Place("p192");
  private Place p197 = new Place("p197");
  private Place p22 = new Place("p22");
  private Place p29 = new Place("p29");
  private Place p30 = new Place("p30");
  private Place p41 = new Place("p41");
  private Place p47 = new Place("p47");
  private Place p53 = new Place("p53");
  private Place p59 = new Place("p59");
  private Place p67 = new Place("p67");
  private Place p74 = new Place("p74");
  private Place p73 = new Place("p73");
  private Place p80 = new Place("p80");
  private Place p84 = new Place("p84");
  private Place p87 = new Place("p87");
  private Place p206 = new Place("p206");
  private Place p96 = new Place("p96");
  private Place p115 = new Place("p115");
  private Place p103 = new Place("p103");
  private Place p109 = new Place("p109");
  private Place p1 = new Place("p1");
  private Place p4 = new Place("p4");
  private Place p7 = new Place("p7");
  private Place p140 = new Place("p140");
  private Place p133 = new Place("p133");
  private Place p121 = new Place("p121");
  private Place p127 = new Place("p127");

  /** Transitions declaration. */
  private Transition t50 = new Transition("t50","return \n(\nSAVIERInstantConditions.verifyConditions(\n(AlertResponse) getTokenSet().get(0).getObject(), \ngetTokenSet().get(0).getTimestamp(),\nCollections.unmodifiableMap(Stream.of(\nentry(\"55505\", Arrays.asList(new Triple(\"Status_Report.Air_Segment_GO_NO_GO\",\"=\",Boolean.TRUE)))\n).collect(entriesToMap()))\n));","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return 
(
SAVIERInstantConditions.verifyConditions((OPResponse) getTokenSet().get(0).getObject(), 
getTokenSet().get(0).getTimestamp(),
Collections.unmodifiableMap(Stream.of(
entry("55505", Arrays.asList(new Triple("Status_Report.Air_Segment_GO_NO_GO","=",Boolean.TRUE)))
).collect(entriesToMap()))
));
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t56 = new Transition("t56","return true;","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return true;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t60 = new Transition("t60","return (\nevaluateInputTokens(this,new TokenEvaluator(){\npublic boolean evaluate(Token token) {\nreturn (\ngetActionTriggerTimestamp(\n(AlertResponse) token.getObject(),\ntoken.getTimestamp(),\n((AlertResponse) token.getObject()).getOperation().getEndTime(),\nCollections.unmodifiableMap(Stream.of(\nentry(\"2001\", Arrays.asList(new Triple(\"selectFPCtrlMode\",\"=\",55)))\n).collect(entriesToMap())),\nSAVIERTimedConditions::verifyConditions\n))!=null;\n}\n})\n);","currentCase = new Token(\ncurrentCase.getObject(),\nSAVIERTimedConditions.verifyConditions(\n(AlertResponse) currentCase.getObject(),\ncurrentCase.getTimestamp(),\n((AlertResponse) currentCase.getObject()).getOperation().getEndTime(),\nCollections.unmodifiableMap(Stream.of(\nentry(\"2001\", Arrays.asList(new Triple(\"selectFPCtrlMode\",\"=\",55)))\n).collect(entriesToMap()))\n))") {
         public boolean evaluate(){
                 return (
evaluateInputTokens(this,new TokenEvaluator(){
public boolean evaluate(Token token) {
return (
getActionTriggerTimestamp((OPResponse) token.getObject(),
token.getTimestamp(),
((OPResponse) token.getObject()).getOperation().getEndTime(),
Collections.unmodifiableMap(Stream.of(
entry("2001", Arrays.asList(new Triple("selectFPCtrlMode","=",55)))
).collect(entriesToMap())),
SAVIERTimedConditions::verifyConditions
))!=null;
}
            })
);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(
currentCase.getObject(),
SAVIERTimedConditions.verifyConditions((OPResponse) currentCase.getObject(),
currentCase.getTimestamp(),
((OPResponse) currentCase.getObject()).getOperation().getEndTime(),
Collections.unmodifiableMap(Stream.of(
entry("2001", Arrays.asList(new Triple("selectFPCtrlMode","=",55)))
).collect(entriesToMap()))
)));
         }
  };
  private Transition t196 = new Transition("t196","return ANDJoinGuard(this);","currentCase = ANDJoinWinner") {
         public boolean evaluate(){
                 return ANDJoinGuard(this);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = ANDJoinWinner);
         }
  };
  private Transition t69 = new Transition("t69","return true;","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return true;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t2 = new Transition("t2","return true;","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return true;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t6 = new Transition("t6","return true;","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return true;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t9 = new Transition("t9","return true;","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return true;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t77 = new Transition("t77","return ANDJoinGuard(this);","currentCase = ANDJoinWinner") {
         public boolean evaluate(){
                 return ANDJoinGuard(this);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = ANDJoinWinner);
         }
  };
  private Transition t82 = new Transition("t82","return true;","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return true;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t86 = new Transition("t86","return true;","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return true;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t89 = new Transition("t89","return true;","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return true;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t98 = new Transition("t98","return \n!(\nSAVIERInstantConditions.verifyConditions(\n(AlertResponse) getTokenSet().get(0).getObject(), \ngetTokenSet().get(0).getTimestamp(),\nCollections.unmodifiableMap(Stream.of(\nentry(\"3001\", Arrays.asList(new Triple(\"selectFPCtrlMode\",\"=\",53)))\n).collect(entriesToMap()))\n));","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return 
!(
SAVIERInstantConditions.verifyConditions((OPResponse) getTokenSet().get(0).getObject(), 
getTokenSet().get(0).getTimestamp(),
Collections.unmodifiableMap(Stream.of(
entry("3001", Arrays.asList(new Triple("selectFPCtrlMode","=",53)))
).collect(entriesToMap()))
));
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t99 = new Transition("t99","return \n(\nSAVIERInstantConditions.verifyConditions(\n(AlertResponse) getTokenSet().get(0).getObject(), \ngetTokenSet().get(0).getTimestamp(),\nCollections.unmodifiableMap(Stream.of(\nentry(\"3001\", Arrays.asList(new Triple(\"selectFPCtrlMode\",\"=\",53)))\n).collect(entriesToMap()))\n));","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return 
(
SAVIERInstantConditions.verifyConditions((OPResponse) getTokenSet().get(0).getObject(), 
getTokenSet().get(0).getTimestamp(),
Collections.unmodifiableMap(Stream.of(
entry("3001", Arrays.asList(new Triple("selectFPCtrlMode","=",53)))
).collect(entriesToMap()))
));
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t203 = new Transition("t203","return (\nevaluateInputTokens(this,new TokenEvaluator(){\npublic boolean evaluate(Token token) {\nreturn (\nSAVIERTimedConditions.verifyConditions(\n(AlertResponse) currentCase.getObject(),\ncurrentCase.getTimestamp(),\n((AlertResponse) currentCase.getObject()).getOperation().getEndTime(),\nCollections.unmodifiableMap(Stream.of(\nentry(\"55006\", Arrays.asList(new Triple(\"AMSSubmode\",\"=\",5)))\n).collect(entriesToMap()))\n))!=null;\n}\n})\n);","currentCase = new Token(\ncurrentCase.getObject(),\nSAVIERTimedConditions.verifyConditions(\n(AlertResponse) currentCase.getObject(),\ncurrentCase.getTimestamp(),\n((AlertResponse) currentCase.getObject()).getOperation().getEndTime(),\nCollections.unmodifiableMap(Stream.of(\nentry(\"55006\", Arrays.asList(new Triple(\"AMSSubmode\",\"=\",5)))\n).collect(entriesToMap()))\n))") {
         public boolean evaluate(){
                 return (
evaluateInputTokens(this,new TokenEvaluator(){
public boolean evaluate(Token token) {
return (
SAVIERTimedConditions.verifyConditions((OPResponse) currentCase.getObject(),
currentCase.getTimestamp(),
((OPResponse) currentCase.getObject()).getOperation().getEndTime(),
Collections.unmodifiableMap(Stream.of(
entry("55006", Arrays.asList(new Triple("AMSSubmode","=",5)))
).collect(entriesToMap()))
))!=null;
}
            })
);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(
currentCase.getObject(),
SAVIERTimedConditions.verifyConditions((OPResponse) currentCase.getObject(),
currentCase.getTimestamp(),
((OPResponse) currentCase.getObject()).getOperation().getEndTime(),
Collections.unmodifiableMap(Stream.of(
entry("55006", Arrays.asList(new Triple("AMSSubmode","=",5)))
).collect(entriesToMap()))
)));
         }
  };
  private Transition t202 = new Transition("t202","return true;","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp() + 5000)") {
         public boolean evaluate(){
                 return true;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp() + 5000));
         }
  };
  private Transition t124 = new Transition("t124","return true;","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return true;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t123 = new Transition("t123","return false;","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return false;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t118 = new Transition("t118","return \n(\nSAVIERInstantConditions.verifyConditions(\n(AlertResponse) getTokenSet().get(0).getObject(), \ngetTokenSet().get(0).getTimestamp(),\nCollections.unmodifiableMap(Stream.of(\nentry(\"3007\", Arrays.asList(new Triple(\"EngineSpeed1\",\">\",2400.0),new Triple(\"EngineSpeed1\",\"<\",7000.0),new Triple(\"EnginePowerSetting\",\"<\",9999.0))),\nentry(\"55253\", Arrays.asList(new Triple(\"CylinderHeadTemperature\",\">\",74.0),new Triple(\"CylinderHeadTemperature\",\"<\",98.0),new Triple(\"Engine_Oil_Level\",\">\",20.0),new Triple(\"Engine_Oil_Level\",\"<\",100.0)))\n).collect(entriesToMap()))\n));","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return 
(
SAVIERInstantConditions.verifyConditions((OPResponse) getTokenSet().get(0).getObject(), 
getTokenSet().get(0).getTimestamp(),
Collections.unmodifiableMap(Stream.of(
entry("3007", Arrays.asList(new Triple("EngineSpeed1",">",2400.0),new Triple("EngineSpeed1","<",7000.0),new Triple("EnginePowerSetting","<",9999.0))),
entry("55253", Arrays.asList(new Triple("CylinderHeadTemperature",">",74.0),new Triple("CylinderHeadTemperature","<",98.0),new Triple("Engine_Oil_Level",">",20.0),new Triple("Engine_Oil_Level","<",100.0)))
).collect(entriesToMap()))
));
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t117 = new Transition("t117","return \n!(\nSAVIERInstantConditions.verifyConditions(\n(AlertResponse) getTokenSet().get(0).getObject(), \ngetTokenSet().get(0).getTimestamp(),\nCollections.unmodifiableMap(Stream.of(\nentry(\"3007\", Arrays.asList(new Triple(\"EngineSpeed1\",\">\",2400.0),new Triple(\"EngineSpeed1\",\"<\",7000.0),new Triple(\"EnginePowerSetting\",\"<\",9999.0))),\nentry(\"55253\", Arrays.asList(new Triple(\"CylinderHeadTemperature\",\">\",74.0),new Triple(\"CylinderHeadTemperature\",\"<\",98.0),new Triple(\"Engine_Oil_Level\",\">\",20.0),new Triple(\"Engine_Oil_Level\",\"<\",100.0)))\n).collect(entriesToMap()))\n));","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return 
!(
SAVIERInstantConditions.verifyConditions((OPResponse) getTokenSet().get(0).getObject(), 
getTokenSet().get(0).getTimestamp(),
Collections.unmodifiableMap(Stream.of(
entry("3007", Arrays.asList(new Triple("EngineSpeed1",">",2400.0),new Triple("EngineSpeed1","<",7000.0),new Triple("EnginePowerSetting","<",9999.0))),
entry("55253", Arrays.asList(new Triple("CylinderHeadTemperature",">",74.0),new Triple("CylinderHeadTemperature","<",98.0),new Triple("Engine_Oil_Level",">",20.0),new Triple("Engine_Oil_Level","<",100.0)))
).collect(entriesToMap()))
));
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t111 = new Transition("t111","return \n!(\nSAVIERInstantConditions.verifyConditions(\n(AlertResponse) getTokenSet().get(0).getObject(), \ngetTokenSet().get(0).getTimestamp(),\nCollections.unmodifiableMap(Stream.of(\nentry(\"3007\", Arrays.asList(new Triple(\"EngineSpeed1\",\">\",8600.0),new Triple(\"EngineSpeed1\",\"<\",9400.0)))\n).collect(entriesToMap()))\n));","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return 
!(
SAVIERInstantConditions.verifyConditions((OPResponse) getTokenSet().get(0).getObject(), 
getTokenSet().get(0).getTimestamp(),
Collections.unmodifiableMap(Stream.of(
entry("3007", Arrays.asList(new Triple("EngineSpeed1",">",8600.0),new Triple("EngineSpeed1","<",9400.0)))
).collect(entriesToMap()))
));
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t112 = new Transition("t112","return \n(\nSAVIERInstantConditions.verifyConditions(\n(AlertResponse) getTokenSet().get(0).getObject(), \ngetTokenSet().get(0).getTimestamp(),\nCollections.unmodifiableMap(Stream.of(\nentry(\"3007\", Arrays.asList(new Triple(\"EngineSpeed1\",\">\",8600.0),new Triple(\"EngineSpeed1\",\"<\",9400.0)))\n).collect(entriesToMap()))\n));","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return 
(
SAVIERInstantConditions.verifyConditions((OPResponse) getTokenSet().get(0).getObject(), 
getTokenSet().get(0).getTimestamp(),
Collections.unmodifiableMap(Stream.of(
entry("3007", Arrays.asList(new Triple("EngineSpeed1",">",8600.0),new Triple("EngineSpeed1","<",9400.0)))
).collect(entriesToMap()))
));
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t104 = new Transition("t104","return \n!(\nSAVIERInstantConditions.verifyConditions(\n(AlertResponse) getTokenSet().get(0).getObject(), \ngetTokenSet().get(0).getTimestamp(),\nCollections.unmodifiableMap(Stream.of(\nentry(\"3007\", Arrays.asList(new Triple(\"EnginePowerSetting\",\">\",58822.0)))\n).collect(entriesToMap()))\n));","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return 
!(
SAVIERInstantConditions.verifyConditions((OPResponse) getTokenSet().get(0).getObject(), 
getTokenSet().get(0).getTimestamp(),
Collections.unmodifiableMap(Stream.of(
entry("3007", Arrays.asList(new Triple("EnginePowerSetting",">",58822.0)))
).collect(entriesToMap()))
));
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t105 = new Transition("t105","return \n(\nSAVIERInstantConditions.verifyConditions(\n(AlertResponse) getTokenSet().get(0).getObject(), \ngetTokenSet().get(0).getTimestamp(),\nCollections.unmodifiableMap(Stream.of(\nentry(\"3007\", Arrays.asList(new Triple(\"EnginePowerSetting\",\">\",58822.0)))\n).collect(entriesToMap()))\n));","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return 
(
SAVIERInstantConditions.verifyConditions((OPResponse) getTokenSet().get(0).getObject(), 
getTokenSet().get(0).getTimestamp(),
Collections.unmodifiableMap(Stream.of(
entry("3007", Arrays.asList(new Triple("EnginePowerSetting",">",58822.0)))
).collect(entriesToMap()))
));
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t144 = new Transition("t144","return true;","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return true;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t136 = new Transition("t136","return (\nevaluateInputTokens(this,new TokenEvaluator(){\npublic boolean evaluate(Token token) {\nreturn (\nSAVIERTimedConditions.verifyConditions(\n(AlertResponse) currentCase.getObject(),\ncurrentCase.getTimestamp(),\n((AlertResponse) currentCase.getObject()).getOperation().getEndTime(),\nCollections.unmodifiableMap(Stream.of(\nentry(\"55001\", Arrays.asList(new Triple(\"calibratedAirSpeed\",\"=\",60)))\n).collect(entriesToMap()))\n))!=null;\n}\n})\n);","currentCase = new Token(\ncurrentCase.getObject(),\nSAVIERTimedConditions.verifyConditions(\n(AlertResponse) currentCase.getObject(),\ncurrentCase.getTimestamp(),\n((AlertResponse) currentCase.getObject()).getOperation().getEndTime(),\nCollections.unmodifiableMap(Stream.of(\nentry(\"55001\", Arrays.asList(new Triple(\"calibratedAirSpeed\",\"=\",80)))\n).collect(entriesToMap()))\n))") {
         public boolean evaluate(){
                 return (
evaluateInputTokens(this,new TokenEvaluator(){
public boolean evaluate(Token token) {
return (
SAVIERTimedConditions.verifyConditions((OPResponse) currentCase.getObject(),
currentCase.getTimestamp(),
((OPResponse) currentCase.getObject()).getOperation().getEndTime(),
Collections.unmodifiableMap(Stream.of(
entry("55001", Arrays.asList(new Triple("calibratedAirSpeed","=",60)))
).collect(entriesToMap()))
))!=null;
}
            })
);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(
currentCase.getObject(),
SAVIERTimedConditions.verifyConditions((OPResponse) currentCase.getObject(),
currentCase.getTimestamp(),
((OPResponse) currentCase.getObject()).getOperation().getEndTime(),
Collections.unmodifiableMap(Stream.of(
entry("55001", Arrays.asList(new Triple("calibratedAirSpeed","=",80)))
).collect(entriesToMap()))
)));
         }
  };
  private Transition t135 = new Transition("t135","return !(\nevaluateInputTokens(this,new TokenEvaluator(){\npublic boolean evaluate(Token token) {\nreturn (\nSAVIERTimedConditions.verifyConditions(\n(AlertResponse) currentCase.getObject(),\ncurrentCase.getTimestamp(),\n((AlertResponse) currentCase.getObject()).getOperation().getEndTime(),\nCollections.unmodifiableMap(Stream.of(\nentry(\"55001\", Arrays.asList(new Triple(\"calibratedAirSpeed\",\"=\",60)))\n).collect(entriesToMap()))\n))!=null;\n}\n})\n);","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return !(
evaluateInputTokens(this,new TokenEvaluator(){
public boolean evaluate(Token token) {
return (
SAVIERTimedConditions.verifyConditions((OPResponse) currentCase.getObject(),
currentCase.getTimestamp(),
((OPResponse) currentCase.getObject()).getOperation().getEndTime(),
Collections.unmodifiableMap(Stream.of(
entry("55001", Arrays.asList(new Triple("calibratedAirSpeed","=",60)))
).collect(entriesToMap()))
))!=null;
}
            })
);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t129 = new Transition("t129","return (\nevaluateInputTokens(this,new TokenEvaluator(){\npublic boolean evaluate(Token token) {\nreturn (\nSAVIERQueriesUtils.verifyValueIncreasing(\n(AlertResponse) token.getObject(),\n\"55001\",\n\"calibratedAirSpeed\",\ntoken.getTimestamp(),\n((AlertResponse) token.getObject()).getOperation().getEndTime(),\n1.0\n))!=null;\n}\n})\n);","currentCase = new Token(\ncurrentCase.getObject(),\nSAVIERQueriesUtils.verifyValueIncreasing(\n(AlertResponse) currentCase.getObject(),\n\"55001\",\n\"calibratedAirSpeed\",\ncurrentCase.getTimestamp(),\n((AlertResponse) currentCase.getObject()).getOperation().getEndTime(),\n5.0\n)\n)") {
         public boolean evaluate(){
                 return (
evaluateInputTokens(this,new TokenEvaluator(){
public boolean evaluate(Token token) {
return (
SAVIERQueriesUtils.verifyValueIncreasing((OPResponse) token.getObject(),
"55001",
"calibratedAirSpeed",
token.getTimestamp(),
((OPResponse) token.getObject()).getOperation().getEndTime(),
1.0
))!=null;
}
            })
);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(
currentCase.getObject(),
SAVIERQueriesUtils.verifyValueIncreasing((OPResponse) currentCase.getObject(),
"55001",
"calibratedAirSpeed",
currentCase.getTimestamp(),
((OPResponse) currentCase.getObject()).getOperation().getEndTime(),
5.0
)
));
         }
  };
  private Transition t128 = new Transition("t128","return !(\nevaluateInputTokens(this,new TokenEvaluator(){\npublic boolean evaluate(Token token) {\nreturn (\nSAVIERQueriesUtils.verifyValueIncreasing(\n(AlertResponse) token.getObject(),\n\"55001\",\n\"calibratedAirSpeed\",\ntoken.getTimestamp(),\n((AlertResponse) token.getObject()).getOperation().getEndTime(),\n1.0\n))!=null;\n}\n})\n);","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp() + 10000)") {
         public boolean evaluate(){
                 return !(
evaluateInputTokens(this,new TokenEvaluator(){
public boolean evaluate(Token token) {
return (
SAVIERQueriesUtils.verifyValueIncreasing((OPResponse) token.getObject(),
"55001",
"calibratedAirSpeed",
token.getTimestamp(),
((OPResponse) token.getObject()).getOperation().getEndTime(),
1.0
))!=null;
}
            })
);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp() + 10000));
         }
  };
  private Transition t162 = new Transition("t162","return (\nevaluateInputTokens(this,new TokenEvaluator(){\npublic boolean evaluate(Token token) {\nreturn (\nSAVIERQueriesUtils.verifyValueIncreasing(\n(AlertResponse) token.getObject(),\n\"55001\",\n\"calibratedAirSpeed\",\ntoken.getTimestamp(),\n((AlertResponse) token.getObject()).getOperation().getEndTime(),\n1.0\n))!=null;\n}\n})\n);","currentCase = new Token(\ncurrentCase.getObject(),\nSAVIERQueriesUtils.verifyValueIncreasing(\n(AlertResponse) currentCase.getObject(),\n\"55001\",\n\"calibratedAirSpeed\",\ncurrentCase.getTimestamp(),\n((AlertResponse) currentCase.getObject()).getOperation().getEndTime(),\n1.0\n)\n)") {
         public boolean evaluate(){
                 return (
evaluateInputTokens(this,new TokenEvaluator(){
public boolean evaluate(Token token) {
return (
SAVIERQueriesUtils.verifyValueIncreasing((OPResponse) token.getObject(),
"55001",
"calibratedAirSpeed",
token.getTimestamp(),
((OPResponse) token.getObject()).getOperation().getEndTime(),
1.0
))!=null;
}
            })
);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(
currentCase.getObject(),
SAVIERQueriesUtils.verifyValueIncreasing((OPResponse) currentCase.getObject(),
"55001",
"calibratedAirSpeed",
currentCase.getTimestamp(),
((OPResponse) currentCase.getObject()).getOperation().getEndTime(),
1.0
)
));
         }
  };
  private Transition t161 = new Transition("t161","return !(\nevaluateInputTokens(this,new TokenEvaluator(){\npublic boolean evaluate(Token token) {\nreturn (\nSAVIERQueriesUtils.verifyValueIncreasing(\n(AlertResponse) token.getObject(),\n\"55001\",\n\"calibratedAirSpeed\",\ntoken.getTimestamp(),\n((AlertResponse) token.getObject()).getOperation().getEndTime(),\n1.0\n))!=null;\n}\n})\n);","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp() + 100000)") {
         public boolean evaluate(){
                 return !(
evaluateInputTokens(this,new TokenEvaluator(){
public boolean evaluate(Token token) {
return (
SAVIERQueriesUtils.verifyValueIncreasing((OPResponse) token.getObject(),
"55001",
"calibratedAirSpeed",
token.getTimestamp(),
((OPResponse) token.getObject()).getOperation().getEndTime(),
1.0
))!=null;
}
            })
);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp() + 100000));
         }
  };
  private Transition t164 = new Transition("t164","return true;","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return true;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t155 = new Transition("t155","return \n(\nSAVIERInstantConditions.verifyConditions(\n(AlertResponse) getTokenSet().get(0).getObject(), \ngetTokenSet().get(0).getTimestamp(),\nCollections.unmodifiableMap(Stream.of(\nentry(\"55006\", Arrays.asList(new Triple(\"weightOnWheels\",\"=\",0)))\n).collect(entriesToMap()))\n));","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return 
(
SAVIERInstantConditions.verifyConditions((OPResponse) getTokenSet().get(0).getObject(), 
getTokenSet().get(0).getTimestamp(),
Collections.unmodifiableMap(Stream.of(
entry("55006", Arrays.asList(new Triple("weightOnWheels","=",0)))
).collect(entriesToMap()))
));
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t150 = new Transition("t150","return true;","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return true;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t23 = new Transition("t23","return ANDJoinGuard(this);","currentCase = ANDJoinWinner") {
         public boolean evaluate(){
                 return ANDJoinGuard(this);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = ANDJoinWinner);
         }
  };
  private Transition t27 = new Transition("t27","return true;","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return true;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t182 = new Transition("t182","return true;","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return true;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t187 = new Transition("t187","return true;","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return true;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t189 = new Transition("t189","return (\nevaluateInputTokens(this,new TokenEvaluator(){\npublic boolean evaluate(Token token) {\nreturn (\ngetActionTriggerTimestamp(\n(AlertResponse) token.getObject(),\ntoken.getTimestamp(),\n((AlertResponse) token.getObject()).getOperation().getEndTime(),\nCollections.unmodifiableMap(Stream.of(\nentry(\"2001\", Arrays.asList(new Triple(\"selectFPCtrlMode\",\"=\",56)))\n).collect(entriesToMap())),\nSAVIERTimedConditions::verifyConditions\n))!=null;\n}\n})\n);","currentCase = new Token(\ncurrentCase.getObject(),\nSAVIERTimedConditions.verifyConditions(\n(AlertResponse) currentCase.getObject(),\ncurrentCase.getTimestamp(),\n((AlertResponse) currentCase.getObject()).getOperation().getEndTime(),\nCollections.unmodifiableMap(Stream.of(\nentry(\"2001\", Arrays.asList(new Triple(\"selectFPCtrlMode\",\"=\",56)))\n).collect(entriesToMap()))\n))") {
         public boolean evaluate(){
                 return (
evaluateInputTokens(this,new TokenEvaluator(){
public boolean evaluate(Token token) {
return (
getActionTriggerTimestamp((OPResponse) token.getObject(),
token.getTimestamp(),
((OPResponse) token.getObject()).getOperation().getEndTime(),
Collections.unmodifiableMap(Stream.of(
entry("2001", Arrays.asList(new Triple("selectFPCtrlMode","=",56)))
).collect(entriesToMap())),
SAVIERTimedConditions::verifyConditions
))!=null;
}
            })
);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(
currentCase.getObject(),
SAVIERTimedConditions.verifyConditions((OPResponse) currentCase.getObject(),
currentCase.getTimestamp(),
((OPResponse) currentCase.getObject()).getOperation().getEndTime(),
Collections.unmodifiableMap(Stream.of(
entry("2001", Arrays.asList(new Triple("selectFPCtrlMode","=",56)))
).collect(entriesToMap()))
)));
         }
  };
  private Transition t183 = new Transition("t183","return \n!(\nSAVIERInstantConditions.verifyConditions(\n(AlertResponse) getTokenSet().get(0).getObject(), \ngetTokenSet().get(0).getTimestamp(),\nCollections.unmodifiableMap(Stream.of(\nentry(\"55006\", Arrays.asList(new Triple(\"weightOnWheels\",\"=\",0)))\n).collect(entriesToMap()))\n));","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return 
!(
SAVIERInstantConditions.verifyConditions((OPResponse) getTokenSet().get(0).getObject(), 
getTokenSet().get(0).getTimestamp(),
Collections.unmodifiableMap(Stream.of(
entry("55006", Arrays.asList(new Triple("weightOnWheels","=",0)))
).collect(entriesToMap()))
));
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t32 = new Transition("t32","return true;","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return true;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t34 = new Transition("t34","return true;","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return true;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t176 = new Transition("t176","return ANDJoinGuard(this);","currentCase = ANDJoinWinner") {
         public boolean evaluate(){
                 return ANDJoinGuard(this);
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = ANDJoinWinner);
         }
  };
  private Transition t44 = new Transition("t44","return \n(\nSAVIERInstantConditions.verifyConditions(\n(AlertResponse) getTokenSet().get(0).getObject(), \ngetTokenSet().get(0).getTimestamp(),\nCollections.unmodifiableMap(Stream.of(\nentry(\"3001\", Arrays.asList(new Triple(\"selectFPCtrlMode\",\"=\",55)))\n).collect(entriesToMap()))\n));","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return 
(
SAVIERInstantConditions.verifyConditions((OPResponse) getTokenSet().get(0).getObject(), 
getTokenSet().get(0).getTimestamp(),
Collections.unmodifiableMap(Stream.of(
entry("3001", Arrays.asList(new Triple("selectFPCtrlMode","=",55)))
).collect(entriesToMap()))
));
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };
  private Transition t49 = new Transition("t49","return \n!(\nSAVIERInstantConditions.verifyConditions(\n(AlertResponse) getTokenSet().get(0).getObject(), \ngetTokenSet().get(0).getTimestamp(),\nCollections.unmodifiableMap(Stream.of(\nentry(\"55505\", Arrays.asList(new Triple(\"Status_Report.Air_Segment_GO_NO_GO\",\"=\",Boolean.TRUE)))\n).collect(entriesToMap()))\n));","currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp())") {
         public boolean evaluate(){
                 return 
!(
SAVIERInstantConditions.verifyConditions((OPResponse) getTokenSet().get(0).getObject(), 
getTokenSet().get(0).getTimestamp(),
Collections.unmodifiableMap(Stream.of(
entry("55505", Arrays.asList(new Triple("Status_Report.Air_Segment_GO_NO_GO","=",Boolean.TRUE)))
).collect(entriesToMap()))
));
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = new Token(currentCase.getObject(),currentCase.getTimestamp()));
         }
  };

  /** Input Arcs declaration. */
  private InputArc i78_p73_t77 = new InputArc("i78_p73_t77",p73,t77, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i205_p197_t203 = new InputArc("i205_p197_t203",p197,t203, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i46_p41_t44 = new InputArc("i46_p41_t44",p41,t44, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i184_p182_t196 = new InputArc("i184_p182_t196",p182,t196, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i24_p18_t23 = new InputArc("i24_p18_t23",p18,t23, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i189_p185_t187 = new InputArc("i189_p185_t187",p185,t187, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i125_p121_t123 = new InputArc("i125_p121_t123",p121,t123, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i171_p160_t164 = new InputArc("i171_p160_t164",p160,t164, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i25_p19_t23 = new InputArc("i25_p19_t23",p19,t23, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i92_p84_t86 = new InputArc("i92_p84_t86",p84,t86, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i126_p121_t124 = new InputArc("i126_p121_t124",p121,t124, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i158_p153_t155 = new InputArc("i158_p153_t155",p153,t155, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i204_p197_t202 = new InputArc("i204_p197_t202",p197,t202, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i51_p47_t49 = new InputArc("i51_p47_t49",p47,t49, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i184_p179_t182 = new InputArc("i184_p179_t182",p179,t182, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i152_p147_t150 = new InputArc("i152_p147_t150",p147,t150, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i3_p1_t2 = new InputArc("i3_p1_t2",p1,t2, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i120_p115_t118 = new InputArc("i120_p115_t118",p115,t118, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i132_p127_t129 = new InputArc("i132_p127_t129",p127,t129, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i65_p59_t56 = new InputArc("i65_p59_t56",p59,t56, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i198_p192_t196 = new InputArc("i198_p192_t196",p192,t196, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i131_p127_t128 = new InputArc("i131_p127_t128",p127,t128, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i13_p7_t9 = new InputArc("i13_p7_t9",p7,t9, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i184_p153_t183 = new InputArc("i184_p153_t183",p153,t183, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i139_p133_t136 = new InputArc("i139_p133_t136",p133,t136, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i169_p159_t162 = new InputArc("i169_p159_t162",p159,t162, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i95_p87_t89 = new InputArc("i95_p87_t89",p87,t89, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i102_p96_t99 = new InputArc("i102_p96_t99",p96,t99, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i177_p172_t176 = new InputArc("i177_p172_t176",p172,t176, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i194_p193_t189 = new InputArc("i194_p193_t189",p193,t189, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i178_p173_t176 = new InputArc("i178_p173_t176",p173,t176, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i108_p103_t105 = new InputArc("i108_p103_t105",p103,t105, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i168_p159_t161 = new InputArc("i168_p159_t161",p159,t161, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i146_p140_t144 = new InputArc("i146_p140_t144",p140,t144, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i119_p115_t117 = new InputArc("i119_p115_t117",p115,t117, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i36_p29_t32 = new InputArc("i36_p29_t32",p29,t32, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i113_p109_t111 = new InputArc("i113_p109_t111",p109,t111, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i28_p22_t27 = new InputArc("i28_p22_t27",p22,t27, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i62_p53_t60 = new InputArc("i62_p53_t60",p53,t60, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i39_p30_t34 = new InputArc("i39_p30_t34",p30,t34, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i138_p133_t135 = new InputArc("i138_p133_t135",p133,t135, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i11_p4_t6 = new InputArc("i11_p4_t6",p4,t6, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i71_p67_t69 = new InputArc("i71_p67_t69",p67,t69, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i101_p96_t98 = new InputArc("i101_p96_t98",p96,t98, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i79_p74_t77 = new InputArc("i79_p74_t77",p74,t77, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i52_p47_t50 = new InputArc("i52_p47_t50",p47,t50, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i114_p109_t112 = new InputArc("i114_p109_t112",p109,t112, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i83_p80_t82 = new InputArc("i83_p80_t82",p80,t82, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };
  private InputArc i107_p103_t104 = new InputArc("i107_p103_t104",p103,t104, "getTokenSet().size()>0" , "currentCase = getTokenSet().get(0)" ) {
         public boolean evaluate() {
                 return getTokenSet().size()>0;
         }
         public TokenSet execute() {
                 return new TokenSet(currentCase = getTokenSet().get(0));
         }
  };

  /** Output Arcs declaration. */
  private OutputArc o21_t9_p19 = new OutputArc("o21_t9_p19",p19,t9, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o42_t34_p41 = new OutputArc("o42_t34_p41",p41,t34, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o106_t99_p103 = new OutputArc("o106_t99_p103",p103,t99, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o76_t69_p74 = new OutputArc("o76_t69_p74",p74,t69, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o66_t60_p59 = new OutputArc("o66_t60_p59",p59,t60, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o40_t27_p29 = new OutputArc("o40_t27_p29",p29,t27, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o182_t98_p193 = new OutputArc("o182_t98_p193",p193,t98, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o122_t118_p121 = new OutputArc("o122_t118_p121",p121,t118, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o187_t123_p193 = new OutputArc("o187_t123_p193",p193,t123, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o37_t32_p30 = new OutputArc("o37_t32_p30",p30,t32, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o184_t161_p193 = new OutputArc("o184_t161_p193",p193,t161, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o189_t135_p193 = new OutputArc("o189_t135_p193",p193,t135, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o167_t155_p160 = new OutputArc("o167_t155_p160",p160,t155, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o54_t50_p53 = new OutputArc("o54_t50_p53",p53,t50, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o110_t105_p109 = new OutputArc("o110_t105_p109",p109,t105, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o48_t44_p47 = new OutputArc("o48_t44_p47",p47,t44, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o17_t2_p7 = new OutputArc("o17_t2_p7",p7,t2, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o166_t155_p159 = new OutputArc("o166_t155_p159",p159,t155, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o191_t176_p185 = new OutputArc("o191_t176_p185",p185,t176, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o174_t164_p173 = new OutputArc("o174_t164_p173",p173,t164, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o16_t2_p4 = new OutputArc("o16_t2_p4",p4,t2, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o186_t202_p193 = new OutputArc("o186_t202_p193",p193,t202, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o194_t182_p192 = new OutputArc("o194_t182_p192",p192,t182, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o75_t56_p73 = new OutputArc("o75_t56_p73",p73,t56, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o26_t23_p22 = new OutputArc("o26_t23_p22",p22,t23, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o201_t196_p197 = new OutputArc("o201_t196_p197",p197,t196, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o130_t124_p127 = new OutputArc("o130_t124_p127",p127,t124, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o93_t86_p87 = new OutputArc("o93_t86_p87",p87,t86, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o90_t82_p84 = new OutputArc("o90_t82_p84",p84,t82, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o81_t77_p80 = new OutputArc("o81_t77_p80",p80,t77, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o156_t150_p153 = new OutputArc("o156_t150_p153",p153,t150, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o188_t128_p193 = new OutputArc("o188_t128_p193",p193,t128, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o142_t136_p140 = new OutputArc("o142_t136_p140",p140,t136, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o20_t6_p18 = new OutputArc("o20_t6_p18",p18,t6, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o134_t129_p133 = new OutputArc("o134_t129_p133",p133,t129, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o190_t176_p179 = new OutputArc("o190_t176_p179",p179,t176, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o190_t189_p206 = new OutputArc("o190_t189_p206",p206,t189, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o116_t112_p115 = new OutputArc("o116_t112_p115",p115,t112, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o148_t144_p147 = new OutputArc("o148_t144_p147",p147,t144, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o195_t104_p193 = new OutputArc("o195_t104_p193",p193,t104, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o183_t187_p182 = new OutputArc("o183_t187_p182",p182,t187, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o97_t89_p96 = new OutputArc("o97_t89_p96",p96,t89, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o185_t111_p193 = new OutputArc("o185_t111_p193",p193,t111, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o185_t183_p193 = new OutputArc("o185_t183_p193",p193,t183, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o72_t60_p67 = new OutputArc("o72_t60_p67",p67,t60, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o175_t162_p172 = new OutputArc("o175_t162_p172",p172,t162, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o186_t117_p193 = new OutputArc("o186_t117_p193",p193,t117, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o207_t203_p206 = new OutputArc("o207_t203_p206",p206,t203, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };
  private OutputArc o187_t49_p193 = new OutputArc("o187_t49_p193",p193,t49, "currentCase.getObject()@currentCase.getTimestamp()" ){
         public TokenSet execute() {
                 return new TokenSet(currentCase.getObject(),currentCase.getTimestamp());
         }
  };

  /** Class NormalTakeOff constructor. */
  public NORMAL_TAKE_OFF_full() {
     setId("n0");
     setLabel("NormalTakeOff");
     setImportText("import MBPFE.AlertResponse;\nimport MBPFE.Constants.SAVIERConstants;\nimport MBPFE.queries.SAVIER.*;\nimport MBPFE.workflow.TokenEvaluator;\nimport MBPFE.utils.Triple;\nimport java.util.Collections;\nimport java.util.stream.Stream;\nimport java.util.Arrays;\nimport static MBPFE.utils.Maps.entriesToMap;\nimport static MBPFE.utils.Maps.entry;");
     p160.setLabel("Substep 16.2");
     addPlace(p160);
     p159.setLabel("Substep 16.1");
     addPlace(p159);
     p153.setLabel("Step 15");
     addPlace(p153);
     p147.setLabel("Step 14");
     addPlace(p147);
     p182.setLabel("p182");
     addPlace(p182);
     p185.setLabel("p185");
     addPlace(p185);
     p179.setLabel("Step 17");
     addPlace(p179);
     p173.setLabel("p173");
     addPlace(p173);
     p172.setLabel("p172");
     addPlace(p172);
     p18.setLabel("p18");
     addPlace(p18);
     p19.setLabel("p19");
     addPlace(p19);
     p193.setLabel("ContingencyRoute");
     addPlace(p193);
     p192.setLabel("p192");
     addPlace(p192);
     p197.setLabel("Step 19");
     addPlace(p197);
     p22.setLabel("Step 2");
     addPlace(p22);
     p29.setLabel("Substep 2.1");
     addPlace(p29);
     p30.setLabel("Substep 2.2");
     addPlace(p30);
     p41.setLabel("Step 3");
     addPlace(p41);
     p47.setLabel("Step 4");
     addPlace(p47);
     p53.setLabel("Step 5");
     addPlace(p53);
     p59.setLabel("Substep 5.1");
     addPlace(p59);
     p67.setLabel("Substep 5.2");
     addPlace(p67);
     p74.setLabel("p74");
     addPlace(p74);
     p73.setLabel("p73");
     addPlace(p73);
     p80.setLabel("Step 6");
     addPlace(p80);
     p84.setLabel("Substep 6.1");
     addPlace(p84);
     p87.setLabel("Substep 6.2");
     addPlace(p87);
     p206.setLabel("END");
     addPlace(p206);
     p96.setLabel("Step 7");
     addPlace(p96);
     p115.setLabel("Step 10");
     addPlace(p115);
     p103.setLabel("Step 8");
     addPlace(p103);
     p109.setLabel("Step 9");
     addPlace(p109);
     p1.setLabel("START");
     addPlace(p1);
     p4.setLabel("Substep 1.1");
     addPlace(p4);
     p7.setLabel("Substep 1.2");
     addPlace(p7);
     p140.setLabel("Step 13");
     addPlace(p140);
     p133.setLabel("p133");
     addPlace(p133);
     p121.setLabel("Step 11");
     addPlace(p121);
     p127.setLabel("Step 12");
     addPlace(p127);
     t50.setLabel("CHECK:GO STATUS is GO:FULFILLED");
     addTransition(t50);
     t56.setLabel("CHECK:TAKE OFF selected (FULFILLED)");
     addTransition(t56);
     t60.setLabel("ACTION:Command TAKE OFF");
     addTransition(t60);
     t196.setLabel("AND-JOIN");
     addTransition(t196);
     t69.setLabel("CHECK:CONFIRM and CANCEL enabled (FULFILLED)");
     addTransition(t69);
     t2.setLabel("ACTION:Command ARM TAKE OFF");
     addTransition(t2);
     t6.setLabel("CHECK:ARM TAKE OFF (FULFILLED)");
     addTransition(t6);
     t9.setLabel("CHECK:CONFIRM and CANCEL (FULFILLED)");
     addTransition(t9);
     t77.setLabel("AND-JOIN");
     addTransition(t77);
     t82.setLabel("ACTION:Press CONFIRM command");
     addTransition(t82);
     t86.setLabel("CHECK:TAKE OFF FLASHES (FULFILLED)");
     addTransition(t86);
     t89.setLabel("SUPERVISION:ARM TAKE OFF green (FULFILLED)");
     addTransition(t89);
     t98.setLabel("CHECK:FLIGHT MODE is TAKE OFF:NOT FULFILLED");
     addTransition(t98);
     t99.setLabel("CHECK:FLIGHT MODE is TAKE OFF:FULFILLED");
     addTransition(t99);
     t203.setLabel("SUPERVISION:FLIGHT SUBMODE changes to ENROUTE:FULFILLED");
     addTransition(t203);
     t202.setLabel("SUPERVISION:FLIGHT SUBMODE changes to ENROUTE:NOT FULFILLED");
     addTransition(t202);
     t124.setLabel("CHECK:Heading and alignment:FULFILLED");
     addTransition(t124);
     t123.setLabel("CHECK:Heading and alignment:NOT FULFILLED");
     addTransition(t123);
     t118.setLabel("CHECK:Engine parameters:FULFILLED");
     addTransition(t118);
     t117.setLabel("CHECK:Engine parameters:NOT FULFILLED");
     addTransition(t117);
     t111.setLabel("CHECK:RPM 4000 rpm:NOT FULFILLED");
     addTransition(t111);
     t112.setLabel("CHECK:RPM 4000 rpm:FULFILLED");
     addTransition(t112);
     t104.setLabel("CHECK:Throttles 50%:NOT FULFILLED");
     addTransition(t104);
     t105.setLabel("CHECK:Throttles 50%:FULFILLED");
     addTransition(t105);
     t144.setLabel("SUPERVISION:Altitude increasing:FULFILLED");
     addTransition(t144);
     t136.setLabel("SUPERVISION:VROT is reached:FULFILLED");
     addTransition(t136);
     t135.setLabel("SUPERVISION:VROT is reached:NOT FULFILLED");
     addTransition(t135);
     t129.setLabel("SUPERVISION:speed increasing:FULFILLED");
     addTransition(t129);
     t128.setLabel("SUPERVISION:speed increasing:NOT FULFILLED");
     addTransition(t128);
     t162.setLabel("SUPERVISION:Altitude and Speed increase:FULFILLED");
     addTransition(t162);
     t161.setLabel("SUPERVISION:Altitude and Speed increase:NOT FULFILLED");
     addTransition(t161);
     t164.setLabel("CHECK:MP in execution (FULFILLED)");
     addTransition(t164);
     t155.setLabel("CHECK:WOW status is AIR:FULFILLED");
     addTransition(t155);
     t150.setLabel("SUPERVISION:Pitch changes:FULFILLED");
     addTransition(t150);
     t23.setLabel("AND-JOIN");
     addTransition(t23);
     t27.setLabel("ACTION:Press CONFIRM Command");
     addTransition(t27);
     t182.setLabel("SUPERVISION:Monitor take off execution in PCMS (FULFILLED)");
     addTransition(t182);
     t187.setLabel("SUPERVISION:Monitor take off execution (FULFILLED)");
     addTransition(t187);
     t189.setLabel("ACTION:ABORT_MISSION");
     addTransition(t189);
     t183.setLabel("CHECK:WOW status is AIR:NOT FULFILLED");
     addTransition(t183);
     t32.setLabel("CHECK:ARM TAKE OFF (FULFILLED)");
     addTransition(t32);
     t34.setLabel("SUPERVISION:ARM TAKE OFF green (FULFILLED)");
     addTransition(t34);
     t176.setLabel("AND-JOIN");
     addTransition(t176);
     t44.setLabel("CHECK: FLIGHT MODE is TAKE OFF ARMED (FULFILLED)");
     addTransition(t44);
     t49.setLabel("CHECK:GO STATUS is GO:NOT FULFILLED");
     addTransition(t49);
     i78_p73_t77.setEvaluateText("getTokenSet().size()>0");
     i78_p73_t77.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i78_p73_t77);
     i205_p197_t203.setEvaluateText("getTokenSet().size()>0");
     i205_p197_t203.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i205_p197_t203);
     i46_p41_t44.setEvaluateText("getTokenSet().size()>0");
     i46_p41_t44.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i46_p41_t44);
     i184_p182_t196.setEvaluateText("getTokenSet().size()>0");
     i184_p182_t196.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i184_p182_t196);
     i24_p18_t23.setEvaluateText("getTokenSet().size()>0");
     i24_p18_t23.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i24_p18_t23);
     i189_p185_t187.setEvaluateText("getTokenSet().size()>0");
     i189_p185_t187.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i189_p185_t187);
     i125_p121_t123.setEvaluateText("getTokenSet().size()>0");
     i125_p121_t123.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i125_p121_t123);
     i171_p160_t164.setEvaluateText("getTokenSet().size()>0");
     i171_p160_t164.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i171_p160_t164);
     i25_p19_t23.setEvaluateText("getTokenSet().size()>0");
     i25_p19_t23.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i25_p19_t23);
     i92_p84_t86.setEvaluateText("getTokenSet().size()>0");
     i92_p84_t86.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i92_p84_t86);
     i126_p121_t124.setEvaluateText("getTokenSet().size()>0");
     i126_p121_t124.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i126_p121_t124);
     i158_p153_t155.setEvaluateText("getTokenSet().size()>0");
     i158_p153_t155.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i158_p153_t155);
     i204_p197_t202.setEvaluateText("getTokenSet().size()>0");
     i204_p197_t202.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i204_p197_t202);
     i51_p47_t49.setEvaluateText("getTokenSet().size()>0");
     i51_p47_t49.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i51_p47_t49);
     i184_p179_t182.setEvaluateText("getTokenSet().size()>0");
     i184_p179_t182.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i184_p179_t182);
     i152_p147_t150.setEvaluateText("getTokenSet().size()>0");
     i152_p147_t150.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i152_p147_t150);
     i3_p1_t2.setEvaluateText("getTokenSet().size()>0");
     i3_p1_t2.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i3_p1_t2);
     i120_p115_t118.setEvaluateText("getTokenSet().size()>0");
     i120_p115_t118.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i120_p115_t118);
     i132_p127_t129.setEvaluateText("getTokenSet().size()>0");
     i132_p127_t129.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i132_p127_t129);
     i65_p59_t56.setEvaluateText("getTokenSet().size()>0");
     i65_p59_t56.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i65_p59_t56);
     i198_p192_t196.setEvaluateText("getTokenSet().size()>0");
     i198_p192_t196.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i198_p192_t196);
     i131_p127_t128.setEvaluateText("getTokenSet().size()>0");
     i131_p127_t128.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i131_p127_t128);
     i13_p7_t9.setEvaluateText("getTokenSet().size()>0");
     i13_p7_t9.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i13_p7_t9);
     i184_p153_t183.setEvaluateText("getTokenSet().size()>0");
     i184_p153_t183.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i184_p153_t183);
     i139_p133_t136.setEvaluateText("getTokenSet().size()>0");
     i139_p133_t136.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i139_p133_t136);
     i169_p159_t162.setEvaluateText("getTokenSet().size()>0");
     i169_p159_t162.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i169_p159_t162);
     i95_p87_t89.setEvaluateText("getTokenSet().size()>0");
     i95_p87_t89.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i95_p87_t89);
     i102_p96_t99.setEvaluateText("getTokenSet().size()>0");
     i102_p96_t99.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i102_p96_t99);
     i177_p172_t176.setEvaluateText("getTokenSet().size()>0");
     i177_p172_t176.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i177_p172_t176);
     i194_p193_t189.setEvaluateText("getTokenSet().size()>0");
     i194_p193_t189.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i194_p193_t189);
     i178_p173_t176.setEvaluateText("getTokenSet().size()>0");
     i178_p173_t176.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i178_p173_t176);
     i108_p103_t105.setEvaluateText("getTokenSet().size()>0");
     i108_p103_t105.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i108_p103_t105);
     i168_p159_t161.setEvaluateText("getTokenSet().size()>0");
     i168_p159_t161.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i168_p159_t161);
     i146_p140_t144.setEvaluateText("getTokenSet().size()>0");
     i146_p140_t144.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i146_p140_t144);
     i119_p115_t117.setEvaluateText("getTokenSet().size()>0");
     i119_p115_t117.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i119_p115_t117);
     i36_p29_t32.setEvaluateText("getTokenSet().size()>0");
     i36_p29_t32.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i36_p29_t32);
     i113_p109_t111.setEvaluateText("getTokenSet().size()>0");
     i113_p109_t111.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i113_p109_t111);
     i28_p22_t27.setEvaluateText("getTokenSet().size()>0");
     i28_p22_t27.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i28_p22_t27);
     i62_p53_t60.setEvaluateText("getTokenSet().size()>0");
     i62_p53_t60.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i62_p53_t60);
     i39_p30_t34.setEvaluateText("getTokenSet().size()>0");
     i39_p30_t34.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i39_p30_t34);
     i138_p133_t135.setEvaluateText("getTokenSet().size()>0");
     i138_p133_t135.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i138_p133_t135);
     i11_p4_t6.setEvaluateText("getTokenSet().size()>0");
     i11_p4_t6.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i11_p4_t6);
     i71_p67_t69.setEvaluateText("getTokenSet().size()>0");
     i71_p67_t69.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i71_p67_t69);
     i101_p96_t98.setEvaluateText("getTokenSet().size()>0");
     i101_p96_t98.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i101_p96_t98);
     i79_p74_t77.setEvaluateText("getTokenSet().size()>0");
     i79_p74_t77.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i79_p74_t77);
     i52_p47_t50.setEvaluateText("getTokenSet().size()>0");
     i52_p47_t50.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i52_p47_t50);
     i114_p109_t112.setEvaluateText("getTokenSet().size()>0");
     i114_p109_t112.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i114_p109_t112);
     i83_p80_t82.setEvaluateText("getTokenSet().size()>0");
     i83_p80_t82.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i83_p80_t82);
     i107_p103_t104.setEvaluateText("getTokenSet().size()>0");
     i107_p103_t104.setExecuteText("currentCase = getTokenSet().get(0)");
     addInputArc(i107_p103_t104);
     addOutputArc(o21_t9_p19);
     addOutputArc(o42_t34_p41);
     addOutputArc(o106_t99_p103);
     addOutputArc(o76_t69_p74);
     addOutputArc(o66_t60_p59);
     addOutputArc(o40_t27_p29);
     addOutputArc(o182_t98_p193);
     addOutputArc(o122_t118_p121);
     addOutputArc(o187_t123_p193);
     addOutputArc(o37_t32_p30);
     addOutputArc(o184_t161_p193);
     addOutputArc(o189_t135_p193);
     addOutputArc(o167_t155_p160);
     addOutputArc(o54_t50_p53);
     addOutputArc(o110_t105_p109);
     addOutputArc(o48_t44_p47);
     addOutputArc(o17_t2_p7);
     addOutputArc(o166_t155_p159);
     addOutputArc(o191_t176_p185);
     addOutputArc(o174_t164_p173);
     addOutputArc(o16_t2_p4);
     addOutputArc(o186_t202_p193);
     addOutputArc(o194_t182_p192);
     addOutputArc(o75_t56_p73);
     addOutputArc(o26_t23_p22);
     addOutputArc(o201_t196_p197);
     addOutputArc(o130_t124_p127);
     addOutputArc(o93_t86_p87);
     addOutputArc(o90_t82_p84);
     addOutputArc(o81_t77_p80);
     addOutputArc(o156_t150_p153);
     addOutputArc(o188_t128_p193);
     addOutputArc(o142_t136_p140);
     addOutputArc(o20_t6_p18);
     addOutputArc(o134_t129_p133);
     addOutputArc(o190_t176_p179);
     addOutputArc(o190_t189_p206);
     addOutputArc(o116_t112_p115);
     addOutputArc(o148_t144_p147);
     addOutputArc(o195_t104_p193);
     addOutputArc(o183_t187_p182);
     addOutputArc(o97_t89_p96);
     addOutputArc(o185_t111_p193);
     addOutputArc(o185_t183_p193);
     addOutputArc(o72_t60_p67);
     addOutputArc(o175_t162_p172);
     addOutputArc(o186_t117_p193);
     addOutputArc(o207_t203_p206);
     addOutputArc(o187_t49_p193);
  }

}
